C++ Insights: Insights.h File Reference
Insights.h File Reference
#include "InsightsOptions.def"
Classes
struct InsightsOptions
Global C++ Insights command line options.
Namespaces
namespace clang
namespace clang::insights
Macros
#define INSIGHTS_OPT(opt, name, deflt, description, category) bool name;
Enumerations
enum class clang::insights::GlobalInserts {
clang::insights::HeaderNew , clang::insights::HeaderException , clang::insights::HeaderUtility , clang::insights::HeaderStddef ,
clang::insights::HeaderAssert , clang::insights::HeaderStdlib , clang::insights::FuncCxaStart , clang::insights::FuncCxaAtExit ,
clang::insights::FuncMalloc , clang::insights::FuncFree , clang::insights::FuncMemset , clang::insights::FuncMemcpy ,
clang::insights::FuncCxaVecNew , clang::insights::FuncCxaVecCtor , clang::insights::FuncCxaVecDel , clang::insights::FuncCxaVecDtor ,
clang::insights::FuncVtableStruct , clang::insights::FuncCxaPureVirtual , clang::insights::MAX
}
Functions
const InsightsOptions & GetInsightsOptions ()
Get the global C++ Insights options.
InsightsOptions & GetInsightsOptionsRW ()
const clang::ASTContext & GetGlobalAST ()
Get access to the ASTContext.
const clang::CompilerInstance & GetGlobalCI ()
Get access to the CompilerInstance.
void clang::insights::EnableGlobalInsert (GlobalInserts idx)
Macro Definition Documentation
INSIGHTS_OPT
#define INSIGHTS_OPT (opt, name, deflt, description, category) bool name;
Definition at line 21 of file Insights.h.
Function Documentation
GetGlobalAST()
const clang::ASTContext & GetGlobalAST () extern
Get access to the ASTContext.
Definition at line 81 of file Insights.cpp.
References gAST.
Referenced by clang::insights::asthelpers::_mkDeclStmt(), clang::insights::asthelpers::AccessMember(), clang::insights::asthelpers::ArraySubscript(), clang::insights::asthelpers::Bool(), clang::insights::asthelpers::Break(), clang::insights::BUILD_OPT_AND(), clang::insights::BuildSuspendVarName(), clang::insights::asthelpers::Call(), clang::insights::asthelpers::Call(), clang::insights::asthelpers::CallMemberFun(), clang::insights::asthelpers::Case(), clang::insights::asthelpers::CastLToRValue(), clang::insights::asthelpers::Catch(), clang::insights::asthelpers::Comment(), clang::insights::asthelpers::ContantArrayTy(), clang::insights::asthelpers::Equal(), clang::insights::EvaluateNTTPAsConstantExpr(), clang::insights::asthelpers::Function(), clang::insights::asthelpers::FunctionBase(), clang::insights::GetRecordLayout(), clang::insights::GetTemporaryName(), clang::insights::GetType(), clang::insights::asthelpers::Goto(), clang::insights::CodeGenerator::HandleLocalStaticNonTrivialClass(), clang::insights::asthelpers::If(), clang::insights::asthelpers::InitList(), clang::insights::CoroutinesCodeGenerator::InsertArg(), clang::insights::CoroutinesCodeGenerator::InsertArg(), clang::insights::CfrontCodeGenerator::InsertArg(), clang::insights::CfrontCodeGenerator::InsertArg(), clang::insights::CodeGenerator::InsertAttribute(), clang::insights::CoroutinesCodeGenerator::InsertCoroutine(), clang::insights::CfrontCodeGenerator::InsertCXXMethodDecl(), clang::insights::CodeGenerator::InsertTemplateArg(), clang::insights::CodeGenerator::InsertTemplateArgsObjectParam(), clang::insights::CodeGenerator::InsertTemplateParameters(), clang::insights::asthelpers::Int32(), clang::insights::asthelpers::Label(), clang::insights::asthelpers::mkBinaryOperator(), clang::insights::asthelpers::mkCompoundStmt(), clang::insights::asthelpers::mkDeclRefExpr(), clang::insights::asthelpers::mkFieldDecl(), clang::insights::asthelpers::mkLabelDecl(), clang::insights::asthelpers::mkNullStmt(), clang::insights::asthelpers::mkStdFunctionDecl(), clang::insights::asthelpers::mkUnaryOperator(), clang::insights::asthelpers::New(), clang::insights::asthelpers::Parameter(), clang::insights::asthelpers::Paren(), clang::insights::ProcessFields(), clang::insights::asthelpers::Ptr(), clang::insights::asthelpers::ReinterpretCast(), clang::insights::asthelpers::Return(), clang::insights::asthelpers::Sizeof(), clang::insights::asthelpers::StaticCast(), clang::insights::asthelpers::Struct(), clang::insights::asthelpers::Switch(), clang::insights::TemporaryDeclFinder::TemporaryDeclFinder(), clang::insights::asthelpers::Throw(), clang::insights::asthelpers::Try(), clang::insights::asthelpers::Typedef(), clang::insights::asthelpers::Variable(), clang::insights::CoroutineASTTransformer::VisitCoroutineBodyStmt(), clang::insights::TemporaryDeclFinder::VisitCXXTemporaryObjectExpr(), and clang::insights::asthelpers::VoidTy().
GetGlobalCI()
const clang::CompilerInstance & GetGlobalCI () extern
Get access to the CompilerInstance.
Definition at line 88 of file Insights.cpp.
References gCI.
Referenced by clang::insights::HasOverload().
GetInsightsOptions()
const InsightsOptions & GetInsightsOptions () extern
Get the global C++ Insights options.
Definition at line 37 of file Insights.cpp.
References gInsightsOptions.
Referenced by clang::insights::LifetimeTracker::Add(), CppInsightASTConsumer::CppInsightASTConsumer(), clang::insights::LifetimeTracker::EndScope(), clang::insights::GetCfrontOverloadedFunctionName(), clang::insights::GetNamePlain(), clang::insights::GetType(), CppInsightASTConsumer::HandleTranslationUnit(), clang::insights::CodeGenerator::InsertFunctionNameWithReturnType(), clang::insights::CodeGenerator::InsertMethodBody(), main(), clang::insights::LifetimeTracker::Return(), clang::insights::LifetimeTracker::StartScope(), clang::insights::TemporaryDeclFinder::TemporaryDeclFinder(), and clang::insights::TemporaryDeclFinder::VisitCXXTemporaryObjectExpr().
GetInsightsOptionsRW()
InsightsOptions & GetInsightsOptionsRW () extern
Definition at line 43 of file Insights.cpp.
References gInsightsOptions.