C++ Insights: InsightsStaticStrings.h File Reference
InsightsStaticStrings.h File Reference
#include <string_view>
Macros
#define KW_CONST "const"
#define KW_AUTO "auto"
#define KW_CONSTEXPR "constexpr"
#define KW_CONSTEVAL "consteval"
#define KW_CONSTINIT "constinit"
#define KW_VOLATILE "volatile"
#define KW_STATIC "static"
#define KW_EXTERN "extern"
#define KW_NOEXCEPT "noexcept"
#define KW_CLASS "class"
#define KW_STRUCT "struct"
#define KW_UNION "union"
#define KW_VIRTUAL "virtual"
#define KW_INLINE "inline"
#define KW_REQUIRES "requires"
#define KW_REINTERPRET_CAST "reinterpret_cast"
#define KW_STATIC_CAST "static_cast"
#define KW_PUBLIC "public"
#define KW_PROTECTED "protected"
#define KW_PRIVATE "private"
#define KW_FINAL "final"
#define KW_SIZEOF "sizeof"
#define KW_ALIGNOF "alignof"
#define KW_OPERATOR "operator"
#define KW_USING "using"
#define KW_FRIEND "friend"
#define KW_EXPLICIT "explicit"
#define KW_TEMPLATE "template"
#define KW_NULLPTR "nullptr"
#define KW_NULL "NULL"
#define KW_ENUM "enum"
#define KW_NAMESPACE "namespace"
#define KW_CONCEPT "concept"
#define KW_DELETE "delete"
#define KW_WHILE "while"
#define KW_BREAK "break"
#define KW_DO "do"
#define KW_CASE "case"
#define KW_GOTO "goto"
#define KW_CONTINUE "continue"
#define KW_SWITCH "switch"
#define KW_TYPEID "typeid"
#define KW_MUTABLE "mutable"
#define KW_RETURN "return"
#define KW_STATIC_ASSERT "static_assert"
#define KW_CO_RETURN "co_return"
#define KW_CO_YIELD "co_yield"
#define KW_CO_AWAIT "co_await"
#define KW_TYPENAME "typename"
#define KW_EQUALS_DEFAULT "= default;"
#define KW_EQUALS_DELETE "= delete;"
#define KW_INTERNAL_THIS "__this"
#define KW_ELIPSIS "..."
#define KW_FALSE "false"
#define KW_TRY "try"
#define HLP_ASSIGN " = "
#define HLP_ARROW " -> "
#define BUILD_KW(kw) " " kw " "
#define BUILD_WITH_SPACE_AFTER(kw) kw " "
#define BUILD_WITH_SPACE_BEFORE(kw) " " kw
Functions
consteval std::string_view KwWithSpaceBefore (std::string_view kw)
consteval std::string_view KwWithSpaceAfter (std::string_view kw)
consteval std::string_view KwWithNoSpace (std::string_view kw)
Variables
constexpr std::string_view KW_OPERATOR_ALL {BUILD_KW(KW_OPERATOR)}
constexpr std::string_view kwNoexcept {KW_NOEXCEPT}
constexpr std::string_view kwRequires {KW_REQUIRES}
constexpr std::string_view kwPublic {KW_PUBLIC}
constexpr std::string_view kwProtected {KW_PROTECTED}
constexpr std::string_view kwPrivate {KW_PRIVATE}
constexpr std::string_view kwReinterpretCast {KW_REINTERPRET_CAST}
constexpr std::string_view kwStaticCast {KW_STATIC_CAST}
constexpr std::string_view kwSizeof {KW_SIZEOF}
constexpr std::string_view kwAlignof {KW_ALIGNOF}
constexpr std::string_view kwUnkown {"unkown"sv}
constexpr std::string_view kwOperator {KwWithNoSpace(KW_OPERATOR_ALL)}
constexpr std::string_view kwTemplate {KW_TEMPLATE}
constexpr std::string_view kwCommentStart {"/*"sv}
constexpr std::string_view kwNullptr {KW_NULLPTR}
constexpr std::string_view kwNull {KW_NULL}
constexpr std::string_view kwNamespace {KW_NAMESPACE}
constexpr std::string_view kwDelete {KW_DELETE}
constexpr std::string_view kwWhile {KW_WHILE}
constexpr std::string_view kwBreak {KW_BREAK}
constexpr std::string_view kwContinue {KW_CONTINUE}
constexpr std::string_view kwSwitch {KW_SWITCH}
constexpr std::string_view kwTypeId {KW_TYPEID}
constexpr std::string_view kwReturn {KW_RETURN}
constexpr std::string_view kwFalse {KW_FALSE}
constexpr std::string_view kwElipsis {KW_ELIPSIS}
constexpr std::string_view kwStaticAssert {KW_STATIC_ASSERT}
constexpr std::string_view kwInternalThis {KW_INTERNAL_THIS}
constexpr std::string_view kwThis {KwWithSpaceAfter(KwWithSpaceAfter(kwInternalThis))}
constexpr std::string_view hlpAssing {HLP_ASSIGN}
constexpr std::string_view hlpArrow {HLP_ARROW}
constexpr std::string_view hlpResumeFn {"resume_fn"sv}
constexpr std::string_view hlpDestroyFn {"destroy_fn"sv}
constexpr std::string_view kwConstExprSpace {BUILD_WITH_SPACE_AFTER(KW_CONSTEXPR)}
constexpr std::string_view kwConstEvalSpace {BUILD_WITH_SPACE_AFTER(KW_CONSTEVAL)}
constexpr std::string_view kwStaticSpace {BUILD_WITH_SPACE_AFTER(KW_STATIC)}
constexpr std::string_view kwClassSpace {BUILD_WITH_SPACE_AFTER(KW_CLASS)}
constexpr std::string_view kwStructSpace {BUILD_WITH_SPACE_AFTER(KW_STRUCT)}
constexpr std::string_view kwEnumSpace {BUILD_WITH_SPACE_AFTER(KW_ENUM)}
constexpr std::string_view kwUnionSpace {BUILD_WITH_SPACE_AFTER(KW_UNION)}
constexpr std::string_view kwVirtualSpace {BUILD_WITH_SPACE_AFTER(KW_VIRTUAL)}
constexpr std::string_view kwInlineSpace {BUILD_WITH_SPACE_AFTER(KW_INLINE)}
constexpr std::string_view kwRequiresSpace {BUILD_WITH_SPACE_AFTER(KW_REQUIRES)}
constexpr std::string_view kwOperatorSpace {KwWithSpaceAfter(KW_OPERATOR_ALL)}
constexpr std::string_view kwCppCommentStartSpace {BUILD_WITH_SPACE_AFTER("//")}
constexpr std::string_view kwUsingSpace {BUILD_WITH_SPACE_AFTER(KW_USING)}
constexpr std::string_view kwFriendSpace {BUILD_WITH_SPACE_AFTER(KW_FRIEND)}
constexpr std::string_view kwExplicitSpace {BUILD_WITH_SPACE_AFTER(KW_EXPLICIT)}
constexpr std::string_view kwTemplateSpace {BUILD_WITH_SPACE_AFTER(KW_TEMPLATE)}
constexpr std::string_view kwNamespaceSpace {BUILD_WITH_SPACE_AFTER(KW_NAMESPACE)}
constexpr std::string_view kwConceptSpace {BUILD_WITH_SPACE_AFTER(KW_CONCEPT)}
constexpr std::string_view kwDoSpace {BUILD_WITH_SPACE_AFTER(KW_DO)}
constexpr std::string_view kwCaseSpace {BUILD_WITH_SPACE_AFTER(KW_CASE)}
constexpr std::string_view kwGotoSpace {BUILD_WITH_SPACE_AFTER(KW_GOTO)}
constexpr std::string_view kwMutableSpace {BUILD_WITH_SPACE_AFTER(KW_MUTABLE)}
constexpr std::string_view kwCoReturnSpace {BUILD_WITH_SPACE_AFTER(KW_CO_RETURN)}
constexpr std::string_view kwCoYieldSpace {BUILD_WITH_SPACE_AFTER(KW_CO_YIELD)}
constexpr std::string_view kwCoAwaitSpace {BUILD_WITH_SPACE_AFTER(KW_CO_AWAIT)}
constexpr std::string_view kwTypeNameSpace {BUILD_WITH_SPACE_AFTER(KW_TYPENAME)}
constexpr std::string_view kwCCommentStartSpace {BUILD_WITH_SPACE_AFTER("/*")}
constexpr std::string_view kwCCommentEndSpace {BUILD_WITH_SPACE_AFTER("*/")}
constexpr std::string_view kwElipsisSpace {BUILD_WITH_SPACE_AFTER(KW_ELIPSIS)}
constexpr std::string_view kwTrySpace {BUILD_WITH_SPACE_AFTER(KW_TRY)}
constexpr std::string_view kwSpaceNoexcept {BUILD_WITH_SPACE_BEFORE(KW_NOEXCEPT)}
constexpr std::string_view kwSpaceConst {BUILD_WITH_SPACE_BEFORE(KW_CONST)}
constexpr std::string_view kwSpaceConstExpr {BUILD_WITH_SPACE_BEFORE(KW_CONSTEXPR)}
constexpr std::string_view kwSpaceVolatile {BUILD_WITH_SPACE_BEFORE(KW_VOLATILE)}
constexpr std::string_view kwSpaceFinal {BUILD_WITH_SPACE_BEFORE(KW_FINAL)}
constexpr std::string_view kwSpaceEqualsDefault {BUILD_WITH_SPACE_BEFORE(KW_EQUALS_DEFAULT)}
constexpr std::string_view kwSpaceEqualsDelete {BUILD_WITH_SPACE_BEFORE(KW_EQUALS_DELETE)}
constexpr std::string_view kwSpaceCCommentEnd {BUILD_WITH_SPACE_BEFORE("*/")}
constexpr std::string_view kwSpaceCCommentEndSpace {BUILD_WITH_SPACE_BEFORE("*/ ")}
constexpr std::string_view memberVariablePointerPrefix {"MemberVarPtr_"}
constexpr std::string_view functionPointerPrefix {"FuncPtr_"}
Macro Definition Documentation
BUILD_KW
#define BUILD_KW (kw) " " kw " "
Definition at line 75 of file InsightsStaticStrings.h.
BUILD_WITH_SPACE_AFTER
#define BUILD_WITH_SPACE_AFTER (kw) kw " "
Definition at line 137 of file InsightsStaticStrings.h.
BUILD_WITH_SPACE_BEFORE
#define BUILD_WITH_SPACE_BEFORE (kw) " " kw
Definition at line 138 of file InsightsStaticStrings.h.
HLP_ARROW
#define HLP_ARROW " -> "
Definition at line 72 of file InsightsStaticStrings.h.
HLP_ASSIGN
#define HLP_ASSIGN " = "
Definition at line 71 of file InsightsStaticStrings.h.
KW_ALIGNOF
#define KW_ALIGNOF "alignof"
Definition at line 37 of file InsightsStaticStrings.h.
KW_AUTO
#define KW_AUTO "auto"
Definition at line 16 of file InsightsStaticStrings.h.
KW_BREAK
#define KW_BREAK "break"
Definition at line 50 of file InsightsStaticStrings.h.
KW_CASE
#define KW_CASE "case"
Definition at line 52 of file InsightsStaticStrings.h.
KW_CLASS
#define KW_CLASS "class"
Definition at line 24 of file InsightsStaticStrings.h.
KW_CO_AWAIT
#define KW_CO_AWAIT "co_await"
Definition at line 62 of file InsightsStaticStrings.h.
KW_CO_RETURN
#define KW_CO_RETURN "co_return"
Definition at line 60 of file InsightsStaticStrings.h.
KW_CO_YIELD
#define KW_CO_YIELD "co_yield"
Definition at line 61 of file InsightsStaticStrings.h.
KW_CONCEPT
#define KW_CONCEPT "concept"
Definition at line 47 of file InsightsStaticStrings.h.
KW_CONST
#define KW_CONST "const"
Definition at line 15 of file InsightsStaticStrings.h.
KW_CONSTEVAL
#define KW_CONSTEVAL "consteval"
Definition at line 18 of file InsightsStaticStrings.h.
KW_CONSTEXPR
#define KW_CONSTEXPR "constexpr"
Definition at line 17 of file InsightsStaticStrings.h.
KW_CONSTINIT
#define KW_CONSTINIT "constinit"
Definition at line 19 of file InsightsStaticStrings.h.
KW_CONTINUE
#define KW_CONTINUE "continue"
Definition at line 54 of file InsightsStaticStrings.h.
KW_DELETE
#define KW_DELETE "delete"
Definition at line 48 of file InsightsStaticStrings.h.
KW_DO
#define KW_DO "do"
Definition at line 51 of file InsightsStaticStrings.h.
KW_ELIPSIS
#define KW_ELIPSIS "..."
Definition at line 67 of file InsightsStaticStrings.h.
KW_ENUM
#define KW_ENUM "enum"
Definition at line 45 of file InsightsStaticStrings.h.
KW_EQUALS_DEFAULT
#define KW_EQUALS_DEFAULT "= default;"
Definition at line 64 of file InsightsStaticStrings.h.
KW_EQUALS_DELETE
#define KW_EQUALS_DELETE "= delete;"
Definition at line 65 of file InsightsStaticStrings.h.
KW_EXPLICIT
#define KW_EXPLICIT "explicit"
Definition at line 41 of file InsightsStaticStrings.h.
KW_EXTERN
#define KW_EXTERN "extern"
Definition at line 22 of file InsightsStaticStrings.h.
KW_FALSE
#define KW_FALSE "false"
Definition at line 68 of file InsightsStaticStrings.h.
KW_FINAL
#define KW_FINAL "final"
Definition at line 35 of file InsightsStaticStrings.h.
KW_FRIEND
#define KW_FRIEND "friend"
Definition at line 40 of file InsightsStaticStrings.h.
KW_GOTO
#define KW_GOTO "goto"
Definition at line 53 of file InsightsStaticStrings.h.
KW_INLINE
#define KW_INLINE "inline"
Definition at line 28 of file InsightsStaticStrings.h.
KW_INTERNAL_THIS
#define KW_INTERNAL_THIS "__this"
Definition at line 66 of file InsightsStaticStrings.h.
KW_MUTABLE
#define KW_MUTABLE "mutable"
Definition at line 57 of file InsightsStaticStrings.h.
KW_NAMESPACE
#define KW_NAMESPACE "namespace"
Definition at line 46 of file InsightsStaticStrings.h.
KW_NOEXCEPT
#define KW_NOEXCEPT "noexcept"
Definition at line 23 of file InsightsStaticStrings.h.
KW_NULL
#define KW_NULL "NULL"
Definition at line 44 of file InsightsStaticStrings.h.
KW_NULLPTR
#define KW_NULLPTR "nullptr"
Definition at line 43 of file InsightsStaticStrings.h.
KW_OPERATOR
#define KW_OPERATOR "operator"
Definition at line 38 of file InsightsStaticStrings.h.
KW_PRIVATE
#define KW_PRIVATE "private"
Definition at line 34 of file InsightsStaticStrings.h.
KW_PROTECTED
#define KW_PROTECTED "protected"
Definition at line 33 of file InsightsStaticStrings.h.
KW_PUBLIC
#define KW_PUBLIC "public"
Definition at line 32 of file InsightsStaticStrings.h.
KW_REINTERPRET_CAST
#define KW_REINTERPRET_CAST "reinterpret_cast"
Definition at line 30 of file InsightsStaticStrings.h.
KW_REQUIRES
#define KW_REQUIRES "requires"
Definition at line 29 of file InsightsStaticStrings.h.
KW_RETURN
#define KW_RETURN "return"
Definition at line 58 of file InsightsStaticStrings.h.
KW_SIZEOF
#define KW_SIZEOF "sizeof"
Definition at line 36 of file InsightsStaticStrings.h.
KW_STATIC
#define KW_STATIC "static"
Definition at line 21 of file InsightsStaticStrings.h.
KW_STATIC_ASSERT
#define KW_STATIC_ASSERT "static_assert"
Definition at line 59 of file InsightsStaticStrings.h.
KW_STATIC_CAST
#define KW_STATIC_CAST "static_cast"
Definition at line 31 of file InsightsStaticStrings.h.
KW_STRUCT
#define KW_STRUCT "struct"
Definition at line 25 of file InsightsStaticStrings.h.
KW_SWITCH
#define KW_SWITCH "switch"
Definition at line 55 of file InsightsStaticStrings.h.
KW_TEMPLATE
#define KW_TEMPLATE "template"
Definition at line 42 of file InsightsStaticStrings.h.
KW_TRY
#define KW_TRY "try"
Definition at line 69 of file InsightsStaticStrings.h.
KW_TYPEID
#define KW_TYPEID "typeid"
Definition at line 56 of file InsightsStaticStrings.h.
KW_TYPENAME
#define KW_TYPENAME "typename"
Definition at line 63 of file InsightsStaticStrings.h.
KW_UNION
#define KW_UNION "union"
Definition at line 26 of file InsightsStaticStrings.h.
KW_USING
#define KW_USING "using"
Definition at line 39 of file InsightsStaticStrings.h.
KW_VIRTUAL
#define KW_VIRTUAL "virtual"
Definition at line 27 of file InsightsStaticStrings.h.
KW_VOLATILE
#define KW_VOLATILE "volatile"
Definition at line 20 of file InsightsStaticStrings.h.
KW_WHILE
#define KW_WHILE "while"
Definition at line 49 of file InsightsStaticStrings.h.
Function Documentation
KwWithNoSpace()
consteval std::string_view KwWithNoSpace (std::string_view kw)
Definition at line 93 of file InsightsStaticStrings.h.
KwWithSpaceAfter()
consteval std::string_view KwWithSpaceAfter (std::string_view kw)
Definition at line 86 of file InsightsStaticStrings.h.
KwWithSpaceBefore()
consteval std::string_view KwWithSpaceBefore (std::string_view kw)
Definition at line 79 of file InsightsStaticStrings.h.
Variable Documentation
functionPointerPrefix
constexpr std::string_view functionPointerPrefix {"FuncPtr_"} inline constexpr
Definition at line 185 of file InsightsStaticStrings.h.
hlpArrow
constexpr std::string_view hlpArrow {HLP_ARROW} inline constexpr
Definition at line 132 of file InsightsStaticStrings.h.
hlpAssing
constexpr std::string_view hlpAssing {HLP_ASSIGN} inline constexpr
Definition at line 131 of file InsightsStaticStrings.h.
Referenced by clang::insights::StructuredBindingsCodeGenerator::InsertArg(), clang::insights::CodeGenerator::InsertFunctionNameWithReturnType(), and clang::insights::CodeGenerator::InsertTemplateParameters().
hlpDestroyFn
constexpr std::string_view hlpDestroyFn {"destroy_fn"sv} inline constexpr
Definition at line 134 of file InsightsStaticStrings.h.
hlpResumeFn
constexpr std::string_view hlpResumeFn {"resume_fn"sv} inline constexpr
Definition at line 133 of file InsightsStaticStrings.h.
Referenced by clang::insights::CoroutinesCodeGenerator::InsertCoroutine().
KW_OPERATOR_ALL
constexpr std::string_view KW_OPERATOR_ALL {BUILD_KW(KW_OPERATOR)} inline constexpr
Definition at line 77 of file InsightsStaticStrings.h.
kwAlignof
constexpr std::string_view kwAlignof {KW_ALIGNOF} inline constexpr
Definition at line 109 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertAttribute().
kwBreak
constexpr std::string_view kwBreak {KW_BREAK} inline constexpr
Definition at line 120 of file InsightsStaticStrings.h.
kwCaseSpace
constexpr std::string_view kwCaseSpace {BUILD_WITH_SPACE_AFTER(KW_CASE)} inline constexpr
Definition at line 159 of file InsightsStaticStrings.h.
kwCCommentEndSpace
constexpr std::string_view kwCCommentEndSpace {BUILD_WITH_SPACE_AFTER("*/")} inline constexpr
Definition at line 167 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertConceptConstraint(), and clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwCCommentStartSpace
constexpr std::string_view kwCCommentStartSpace {BUILD_WITH_SPACE_AFTER("/*")} inline constexpr
Definition at line 166 of file InsightsStaticStrings.h.
kwClassSpace
constexpr std::string_view kwClassSpace {BUILD_WITH_SPACE_AFTER(KW_CLASS)} inline constexpr
Definition at line 143 of file InsightsStaticStrings.h.
Referenced by clang::insights::GetTagDeclTypeName(), and clang::insights::CodeGenerator::InsertTemplateParameters().
kwCoAwaitSpace
constexpr std::string_view kwCoAwaitSpace {BUILD_WITH_SPACE_AFTER(KW_CO_AWAIT)} inline constexpr
Definition at line 164 of file InsightsStaticStrings.h.
kwCommentStart
constexpr std::string_view kwCommentStart {"/*"sv} inline constexpr
Definition at line 114 of file InsightsStaticStrings.h.
Referenced by clang::insights::GetNoExcept(), clang::insights::CodeGenerator::InsertConceptConstraint(), and clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwConceptSpace
constexpr std::string_view kwConceptSpace {BUILD_WITH_SPACE_AFTER(KW_CONCEPT)} inline constexpr
Definition at line 157 of file InsightsStaticStrings.h.
kwConstEvalSpace
constexpr std::string_view kwConstEvalSpace {BUILD_WITH_SPACE_AFTER(KW_CONSTEVAL)} inline constexpr
Definition at line 141 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwConstExprSpace
constexpr std::string_view kwConstExprSpace {BUILD_WITH_SPACE_AFTER(KW_CONSTEXPR)} inline constexpr
Definition at line 140 of file InsightsStaticStrings.h.
Referenced by clang::insights::GetQualifiers(), and clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwContinue
constexpr std::string_view kwContinue {KW_CONTINUE} inline constexpr
Definition at line 121 of file InsightsStaticStrings.h.
kwCoReturnSpace
constexpr std::string_view kwCoReturnSpace {BUILD_WITH_SPACE_AFTER(KW_CO_RETURN)} inline constexpr
Definition at line 162 of file InsightsStaticStrings.h.
Referenced by clang::insights::CoroutinesCodeGenerator::InsertArg().
kwCoYieldSpace
constexpr std::string_view kwCoYieldSpace {BUILD_WITH_SPACE_AFTER(KW_CO_YIELD)} inline constexpr
Definition at line 163 of file InsightsStaticStrings.h.
kwCppCommentStartSpace
constexpr std::string_view kwCppCommentStartSpace {BUILD_WITH_SPACE_AFTER("//")} inline constexpr
Definition at line 151 of file InsightsStaticStrings.h.
Referenced by clang::insights::UsingCodeGenerator::InsertArg(), and clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwDelete
constexpr std::string_view kwDelete {KW_DELETE} inline constexpr
Definition at line 118 of file InsightsStaticStrings.h.
kwDoSpace
constexpr std::string_view kwDoSpace {BUILD_WITH_SPACE_AFTER(KW_DO)} inline constexpr
Definition at line 158 of file InsightsStaticStrings.h.
kwElipsis
constexpr std::string_view kwElipsis {KW_ELIPSIS} inline constexpr
Definition at line 126 of file InsightsStaticStrings.h.
Referenced by clang::insights::OutputFormatHelper::AppendParameterList(), and clang::insights::Ellipsis().
kwElipsisSpace
constexpr std::string_view kwElipsisSpace {BUILD_WITH_SPACE_AFTER(KW_ELIPSIS)} inline constexpr
Definition at line 168 of file InsightsStaticStrings.h.
Referenced by clang::insights::EllipsisSpace(), and clang::insights::CodeGenerator::InsertTemplateParameters().
kwEnumSpace
constexpr std::string_view kwEnumSpace {BUILD_WITH_SPACE_AFTER(KW_ENUM)} inline constexpr
Definition at line 145 of file InsightsStaticStrings.h.
kwExplicitSpace
constexpr std::string_view kwExplicitSpace {BUILD_WITH_SPACE_AFTER(KW_EXPLICIT)} inline constexpr
Definition at line 154 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwFalse
constexpr std::string_view kwFalse {KW_FALSE} inline constexpr
Definition at line 125 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::GetValueOfValueInit().
kwFriendSpace
constexpr std::string_view kwFriendSpace {BUILD_WITH_SPACE_AFTER(KW_FRIEND)} inline constexpr
Definition at line 153 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwGotoSpace
constexpr std::string_view kwGotoSpace {BUILD_WITH_SPACE_AFTER(KW_GOTO)} inline constexpr
Definition at line 160 of file InsightsStaticStrings.h.
kwInlineSpace
constexpr std::string_view kwInlineSpace {BUILD_WITH_SPACE_AFTER(KW_INLINE)} inline constexpr
Definition at line 148 of file InsightsStaticStrings.h.
Referenced by clang::insights::GetQualifiers(), and clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwInternalThis
constexpr std::string_view kwInternalThis {KW_INTERNAL_THIS} inline constexpr
Definition at line 128 of file InsightsStaticStrings.h.
Referenced by clang::insights::GetFieldDeclNameForLambda(), clang::insights::CoroutinesCodeGenerator::InsertArg(), clang::insights::LambdaCodeGenerator::InsertArg(), and clang::insights::CoroutineASTTransformer::VisitCXXThisExpr().
kwMutableSpace
constexpr std::string_view kwMutableSpace {BUILD_WITH_SPACE_AFTER(KW_MUTABLE)} inline constexpr
Definition at line 161 of file InsightsStaticStrings.h.
kwNamespace
constexpr std::string_view kwNamespace {KW_NAMESPACE} inline constexpr
Definition at line 117 of file InsightsStaticStrings.h.
kwNamespaceSpace
constexpr std::string_view kwNamespaceSpace {BUILD_WITH_SPACE_AFTER(KW_NAMESPACE)} inline constexpr
Definition at line 156 of file InsightsStaticStrings.h.
kwNoexcept
constexpr std::string_view kwNoexcept {KW_NOEXCEPT} inline constexpr
Definition at line 101 of file InsightsStaticStrings.h.
kwNull
constexpr std::string_view kwNull {KW_NULL} inline constexpr
Definition at line 116 of file InsightsStaticStrings.h.
kwNullptr
constexpr std::string_view kwNullptr {KW_NULLPTR} inline constexpr
Definition at line 115 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::GetValueOfValueInit(), and clang::insights::CodeGenerator::InsertTemplateArg().
kwOperator
constexpr std::string_view kwOperator {KwWithNoSpace(KW_OPERATOR_ALL)} inline constexpr
Definition at line 111 of file InsightsStaticStrings.h.
Referenced by clang::insights::GetName().
kwOperatorSpace
constexpr std::string_view kwOperatorSpace {KwWithSpaceAfter(KW_OPERATOR_ALL)} inline constexpr
Definition at line 150 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwPrivate
constexpr std::string_view kwPrivate {KW_PRIVATE} inline constexpr
Definition at line 105 of file InsightsStaticStrings.h.
kwProtected
constexpr std::string_view kwProtected {KW_PROTECTED} inline constexpr
Definition at line 104 of file InsightsStaticStrings.h.
kwPublic
constexpr std::string_view kwPublic {KW_PUBLIC} inline constexpr
Definition at line 103 of file InsightsStaticStrings.h.
kwReinterpretCast
constexpr std::string_view kwReinterpretCast {KW_REINTERPRET_CAST} inline constexpr
Definition at line 106 of file InsightsStaticStrings.h.
Referenced by clang::insights::GetCastName(), and clang::insights::GetName().
kwRequires
constexpr std::string_view kwRequires {KW_REQUIRES} inline constexpr
Definition at line 102 of file InsightsStaticStrings.h.
kwRequiresSpace
constexpr std::string_view kwRequiresSpace {BUILD_WITH_SPACE_AFTER(KW_REQUIRES)} inline constexpr
Definition at line 149 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertConceptConstraint().
kwReturn
constexpr std::string_view kwReturn {KW_RETURN} inline constexpr
Definition at line 124 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertCXXMethodDecl(), and clang::insights::CodeGenerator::InsertLambdaStaticInvoker().
kwSizeof
constexpr std::string_view kwSizeof {KW_SIZEOF} inline constexpr
Definition at line 108 of file InsightsStaticStrings.h.
kwSpaceCCommentEnd
constexpr std::string_view kwSpaceCCommentEnd {BUILD_WITH_SPACE_BEFORE("*/")} inline constexpr
Definition at line 179 of file InsightsStaticStrings.h.
Referenced by clang::insights::GetNoExcept(), and clang::insights::ToDo().
kwSpaceCCommentEndSpace
constexpr std::string_view kwSpaceCCommentEndSpace {BUILD_WITH_SPACE_BEFORE("*/ ")} inline constexpr
Definition at line 182 of file InsightsStaticStrings.h.
kwSpaceConst
constexpr std::string_view kwSpaceConst {BUILD_WITH_SPACE_BEFORE(KW_CONST)} inline constexpr
Definition at line 173 of file InsightsStaticStrings.h.
Referenced by clang::insights::GetConst().
kwSpaceConstExpr
constexpr std::string_view kwSpaceConstExpr {BUILD_WITH_SPACE_BEFORE(KW_CONSTEXPR)} inline constexpr
Definition at line 174 of file InsightsStaticStrings.h.
kwSpaceEqualsDefault
constexpr std::string_view kwSpaceEqualsDefault {BUILD_WITH_SPACE_BEFORE(KW_EQUALS_DEFAULT)} inline constexpr
Definition at line 177 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertCXXMethodHeader().
kwSpaceEqualsDelete
constexpr std::string_view kwSpaceEqualsDelete {BUILD_WITH_SPACE_BEFORE(KW_EQUALS_DELETE)} inline constexpr
Definition at line 178 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertCXXMethodHeader().
kwSpaceFinal
constexpr std::string_view kwSpaceFinal {BUILD_WITH_SPACE_BEFORE(KW_FINAL)} inline constexpr
Definition at line 176 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwSpaceNoexcept
constexpr std::string_view kwSpaceNoexcept {BUILD_WITH_SPACE_BEFORE(KW_NOEXCEPT)} inline constexpr
Definition at line 172 of file InsightsStaticStrings.h.
Referenced by clang::insights::GetNoExcept().
kwSpaceVolatile
constexpr std::string_view kwSpaceVolatile {BUILD_WITH_SPACE_BEFORE(KW_VOLATILE)} inline constexpr
Definition at line 175 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwStaticAssert
constexpr std::string_view kwStaticAssert {KW_STATIC_ASSERT} inline constexpr
Definition at line 127 of file InsightsStaticStrings.h.
kwStaticCast
constexpr std::string_view kwStaticCast {KW_STATIC_CAST} inline constexpr
Definition at line 107 of file InsightsStaticStrings.h.
Referenced by clang::insights::GetCastName().
kwStaticSpace
constexpr std::string_view kwStaticSpace {BUILD_WITH_SPACE_AFTER(KW_STATIC)} inline constexpr
Definition at line 142 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwStructSpace
constexpr std::string_view kwStructSpace {BUILD_WITH_SPACE_AFTER(KW_STRUCT)} inline constexpr
Definition at line 144 of file InsightsStaticStrings.h.
Referenced by clang::insights::GetTagDeclTypeName().
kwSwitch
constexpr std::string_view kwSwitch {KW_SWITCH} inline constexpr
Definition at line 122 of file InsightsStaticStrings.h.
kwTemplate
constexpr std::string_view kwTemplate {KW_TEMPLATE} inline constexpr
Definition at line 113 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertTemplateParameters().
kwTemplateSpace
constexpr std::string_view kwTemplateSpace {BUILD_WITH_SPACE_AFTER(KW_TEMPLATE)} inline constexpr
Definition at line 155 of file InsightsStaticStrings.h.
Referenced by clang::insights::details::BuildNamespace(), clang::insights::CodeGenerator::InsertQualifierAndName(), and clang::insights::CodeGenerator::InsertTemplateParameters().
kwThis
constexpr std::string_view kwThis {KwWithSpaceAfter(KwWithSpaceAfter(kwInternalThis))} inline constexpr
Definition at line 129 of file InsightsStaticStrings.h.
kwTrySpace
constexpr std::string_view kwTrySpace {BUILD_WITH_SPACE_AFTER(KW_TRY)} inline constexpr
Definition at line 169 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::HandleLocalStaticNonTrivialClass(), and clang::insights::CodeGenerator::InsertMethodBody().
kwTypeId
constexpr std::string_view kwTypeId {KW_TYPEID} inline constexpr
Definition at line 123 of file InsightsStaticStrings.h.
kwTypeNameSpace
constexpr std::string_view kwTypeNameSpace {BUILD_WITH_SPACE_AFTER(KW_TYPENAME)} inline constexpr
Definition at line 165 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertTemplateParameters().
kwUnionSpace
constexpr std::string_view kwUnionSpace {BUILD_WITH_SPACE_AFTER(KW_UNION)} inline constexpr
Definition at line 146 of file InsightsStaticStrings.h.
Referenced by clang::insights::GetTagDeclTypeName().
kwUnkown
constexpr std::string_view kwUnkown {"unkown"sv} inline constexpr
Definition at line 110 of file InsightsStaticStrings.h.
kwUsingSpace
constexpr std::string_view kwUsingSpace {BUILD_WITH_SPACE_AFTER(KW_USING)} inline constexpr
Definition at line 152 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwVirtualSpace
constexpr std::string_view kwVirtualSpace {BUILD_WITH_SPACE_AFTER(KW_VIRTUAL)} inline constexpr
Definition at line 147 of file InsightsStaticStrings.h.
Referenced by clang::insights::CodeGenerator::InsertFunctionNameWithReturnType().
kwWhile
constexpr std::string_view kwWhile {KW_WHILE} inline constexpr
Definition at line 119 of file InsightsStaticStrings.h.
memberVariablePointerPrefix
constexpr std::string_view memberVariablePointerPrefix {"MemberVarPtr_"} inline constexpr
Definition at line 184 of file InsightsStaticStrings.h.