C++ Insights: clang::insights::CoroutineASTTransformer Class Reference
clang::insights::CoroutineASTTransformer Class Reference
Find a SuspendsExpr's in a coroutine body statement for early transformation.
Public Member Functions
CoroutineASTTransformer (CoroutineASTData &coroutineASTData, size_t &suspendsCounter, Stmt *stmt, llvm::DenseMap< VarDecl *, MemberExpr * > varNamePrefix, Stmt *prev=nullptr)
void Visit (Stmt *stmt)
void VisitCompoundStmt (CompoundStmt *stmt)
void VisitSwitchStmt (SwitchStmt *stmt)
void VisitDoStmt (DoStmt *stmt)
void VisitWhileStmt (WhileStmt *stmt)
void VisitIfStmt (IfStmt *stmt)
void VisitForStmt (ForStmt *stmt)
void VisitCXXForRangeStmt (CXXForRangeStmt *stmt)
void VisitDeclRefExpr (DeclRefExpr *stmt)
void VisitDeclStmt (DeclStmt *stmt)
void VisitCXXThisExpr (CXXThisExpr *stmt)
void VisitCallExpr (CallExpr *stmt)
void VisitCXXMemberCallExpr (CXXMemberCallExpr *stmt)
void VisitCoreturnStmt (CoreturnStmt *stmt)
void VisitCoyieldExpr (CoyieldExpr *stmt)
void VisitCoawaitExpr (CoawaitExpr *stmt)
void VisitCoroutineBodyStmt (CoroutineBodyStmt *stmt)
void VisitStmt (Stmt *stmt)
Detailed Description
Find a SuspendsExpr's in a coroutine body statement for early transformation.
Traverse the whole CoroutineBodyStmt to find all appearing VarDecl. These need to be rerouted to the coroutine frame and hence prefixed by something like __f->. For that reason we only look for VarDecls directly appearing in the body, CallExpr will be skipped.
Definition at line 108 of file CoroutinesCodeGenerator.cpp.
Constructor & Destructor Documentation
CoroutineASTTransformer()
clang::insights::CoroutineASTTransformer::CoroutineASTTransformer (CoroutineASTData & coroutineASTData, size_t & suspendsCounter, Stmt * stmt, llvm::DenseMap< VarDecl *, MemberExpr * > varNamePrefix, Stmt * prev = nullptr) inline
Definition at line 119 of file CoroutinesCodeGenerator.cpp.
References Visit().
Member Function Documentation
Visit()
void clang::insights::CoroutineASTTransformer::Visit (Stmt * stmt) inline
Definition at line 136 of file CoroutinesCodeGenerator.cpp.
Referenced by CoroutineASTTransformer(), VisitCallExpr(), VisitCoawaitExpr(), VisitCompoundStmt(), VisitCoreturnStmt(), VisitCoroutineBodyStmt(), VisitCoyieldExpr(), VisitCXXForRangeStmt(), VisitCXXMemberCallExpr(), VisitDeclStmt(), VisitDoStmt(), VisitForStmt(), VisitIfStmt(), VisitStmt(), VisitSwitchStmt(), and VisitWhileStmt().
VisitCallExpr()
void clang::insights::CoroutineASTTransformer::VisitCallExpr (CallExpr * stmt) inline
Definition at line 278 of file CoroutinesCodeGenerator.cpp.
References Visit().
VisitCoawaitExpr()
void clang::insights::CoroutineASTTransformer::VisitCoawaitExpr (CoawaitExpr * stmt) inline
Definition at line 320 of file CoroutinesCodeGenerator.cpp.
References clang::insights::asthelpers::StmtsContainer::Add(), clang::insights::BuildSuspendVarName(), clang::insights::CORO_FRAME_ACCESS, clang::insights::asthelpers::mkDeclRefExpr(), clang::insights::asthelpers::ReplaceNode(), clang::insights::StrCat(), clang::insights::asthelpers::Variable(), and Visit().
VisitCompoundStmt()
void clang::insights::CoroutineASTTransformer::VisitCompoundStmt (CompoundStmt * stmt) inline
Definition at line 143 of file CoroutinesCodeGenerator.cpp.
References clang::insights::asthelpers::StmtsContainer::Add(), clang::insights::asthelpers::StmtsContainer::clear(), clang::insights::asthelpers::mkCompoundStmt(), clang::insights::asthelpers::ReplaceNode(), and Visit().
VisitCoreturnStmt()
void clang::insights::CoroutineASTTransformer::VisitCoreturnStmt (CoreturnStmt * stmt) inline
Definition at line 302 of file CoroutinesCodeGenerator.cpp.
References Visit().
VisitCoroutineBodyStmt()
void clang::insights::CoroutineASTTransformer::VisitCoroutineBodyStmt (CoroutineBodyStmt * stmt) inline
Definition at line 348 of file CoroutinesCodeGenerator.cpp.
References clang::insights::asthelpers::AccessMember(), clang::insights::AddField(), clang::insights::FindDeclRef(), GetGlobalAST(), clang::insights::GetName(), clang::insights::INITIAL_AWAIT_SUSPEND_CALLED_NAME, clang::insights::CoroutineASTData::mFrameAccessDeclRef, clang::insights::CoroutineASTData::mInitialAwaitResumeCalledAccess, clang::insights::CoroutineASTData::mInitialAwaitResumeCalledField, clang::insights::CoroutineASTData::mPromiseField, clang::insights::CoroutineASTData::mSuspendIndexAccess, clang::insights::CoroutineASTData::mSuspendIndexField, clang::insights::SUSPEND_INDEX_NAME, and Visit().
VisitCoyieldExpr()
void clang::insights::CoroutineASTTransformer::VisitCoyieldExpr (CoyieldExpr * stmt) inline
Definition at line 308 of file CoroutinesCodeGenerator.cpp.
References clang::insights::asthelpers::StmtsContainer::Add(), and Visit().
VisitCXXForRangeStmt()
void clang::insights::CoroutineASTTransformer::VisitCXXForRangeStmt (CXXForRangeStmt * stmt) inline
Definition at line 219 of file CoroutinesCodeGenerator.cpp.
References Visit().
VisitCXXMemberCallExpr()
void clang::insights::CoroutineASTTransformer::VisitCXXMemberCallExpr (CXXMemberCallExpr * stmt) inline
Definition at line 290 of file CoroutinesCodeGenerator.cpp.
References Visit().
VisitCXXThisExpr()
void clang::insights::CoroutineASTTransformer::VisitCXXThisExpr (CXXThisExpr * stmt) inline
Definition at line 266 of file CoroutinesCodeGenerator.cpp.
References clang::insights::asthelpers::AccessMember(), kwInternalThis, clang::insights::CoroutineASTData::mFrameAccessDeclRef, clang::insights::CoroutineASTData::mFrameType, clang::insights::asthelpers::mkFieldDecl(), clang::insights::CoroutineASTData::mThisExprs, and clang::insights::asthelpers::ReplaceNode().
VisitDeclRefExpr()
void clang::insights::CoroutineASTTransformer::VisitDeclRefExpr (DeclRefExpr * stmt) inline
Definition at line 228 of file CoroutinesCodeGenerator.cpp.
References clang::insights::Contains(), clang::insights::asthelpers::ReplaceNode(), and RETURN_IF.
VisitDeclStmt()
void clang::insights::CoroutineASTTransformer::VisitDeclStmt (DeclStmt * stmt) inline
Definition at line 239 of file CoroutinesCodeGenerator.cpp.
References clang::insights::asthelpers::AccessMember(), clang::insights::asthelpers::StmtsContainer::Add(), clang::insights::AddField(), clang::insights::asthelpers::Assign(), clang::insights::GetName(), clang::insights::CoroutineASTData::mFrameAccessDeclRef, clang::insights::CoroutineASTData::mFrameType, and Visit().
VisitDoStmt()
void clang::insights::CoroutineASTTransformer::VisitDoStmt (DoStmt * stmt) inline
Definition at line 170 of file CoroutinesCodeGenerator.cpp.
References Visit().
VisitForStmt()
void clang::insights::CoroutineASTTransformer::VisitForStmt (ForStmt * stmt) inline
Definition at line 193 of file CoroutinesCodeGenerator.cpp.
References clang::insights::asthelpers::StmtsContainer::mStmts, clang::insights::asthelpers::ReplaceNode(), and Visit().
VisitIfStmt()
void clang::insights::CoroutineASTTransformer::VisitIfStmt (IfStmt * stmt) inline
Definition at line 184 of file CoroutinesCodeGenerator.cpp.
References Visit().
VisitStmt()
void clang::insights::CoroutineASTTransformer::VisitStmt (Stmt * stmt) inline
Definition at line 396 of file CoroutinesCodeGenerator.cpp.
References Visit().
VisitSwitchStmt()
void clang::insights::CoroutineASTTransformer::VisitSwitchStmt (SwitchStmt * stmt) inline
Definition at line 163 of file CoroutinesCodeGenerator.cpp.
References Visit().
VisitWhileStmt()
void clang::insights::CoroutineASTTransformer::VisitWhileStmt (WhileStmt * stmt) inline
Definition at line 177 of file CoroutinesCodeGenerator.cpp.
References Visit().
The documentation for this class was generated from the following file:
CoroutinesCodeGenerator.cpp