C++ Insights: clang::insights::details::SimpleTypePrinter Class Reference
clang::insights::details::SimpleTypePrinter Class Reference
SimpleTypePrinter a partially substitution of Clang's TypePrinter.
Public Member Functions
SimpleTypePrinter (const QualType &qt, const CppInsightsPrintingPolicy &printingPolicy)
std::string & GetString ()
bool GetTypeString ()
Detailed Description
SimpleTypePrinter a partially substitution of Clang's TypePrinter.
With Clang 9 there seems to be a change in lib/AST/TypePrinter.cpp in printTemplateTypeParmBefore. It now inserts auto when it is a lambda auto parameter. Which is correct, but C++ Insights needs the template parameter name to make up compiling code. Hence, this if "overrides" the implementation of TypePrinter in that case.
It also drops some former code which handled ClassTemplateSpecializationDecl in a special way. Here the template parameters can be lambdas. Those they need a proper name.
Definition at line 439 of file InsightsHelpers.cpp.
Constructor & Destructor Documentation
SimpleTypePrinter()
clang::insights::details::SimpleTypePrinter::SimpleTypePrinter (const QualType & qt, const CppInsightsPrintingPolicy & printingPolicy) inline
Definition at line 812 of file InsightsHelpers.cpp.
Member Function Documentation
GetString()
std::string& clang::insights::details::SimpleTypePrinter::GetString () inline
Definition at line 818 of file InsightsHelpers.cpp.
References clang::insights::OutputFormatHelper::GetString().
GetTypeString()
bool clang::insights::details::SimpleTypePrinter::GetTypeString () inline
Definition at line 820 of file InsightsHelpers.cpp.
References clang::insights::OutputFormatHelper::Append().
Referenced by clang::insights::details::GetName().
The documentation for this class was generated from the following file:
InsightsHelpers.cpp