C++Insights: clang::insights::CompilerGeneratedHandler Class Reference
clang::insights::CompilerGeneratedHandler Class Reference final
Show which special members the compiler generates for a certain class.
#include "/home/builder/CompilerGeneratedHandler.h"
Public Member Functions
CompilerGeneratedHandler (Rewriter &rewrite, ast_matchers::MatchFinder &Matcher)
void run (const ast_matchers::MatchFinder::MatchResult &result) override
Additional Inherited Members
Protected Member Functions inherited from clang::insights::InsightsBase
InsightsBase (Rewriter &rewriter)
void InsertIndentedText (SourceLocation loc, OutputFormatHelper &outputFormatHelper)
Protected Attributes inherited from clang::insights::InsightsBase
Rewriter & mRewrite
Detailed Description
Show which special members the compiler generates for a certain class.
Conveniently the compiler generates special member for us. Like the default constructor, copy or move operators. Under certain circumstances it stops generating. This matches makes it visible.
Definition at line 26 of file CompilerGeneratedHandler.h.
Constructor & Destructor Documentation
CompilerGeneratedHandler()
clang::insights::CompilerGeneratedHandler::CompilerGeneratedHandler (Rewriter & rewrite, ast_matchers::MatchFinder & Matcher)
Definition at line 22 of file CompilerGeneratedHandler.cpp.
References clang::ast_matchers::isTemplate.
Member Function Documentation
run()
void clang::insights::CompilerGeneratedHandler::run (const ast_matchers::MatchFinder::MatchResult & result) override
Definition at line 36 of file CompilerGeneratedHandler.cpp.
References clang::insights::GetEndLoc(), clang::insights::CodeGenerator::InsertAccessModifierAndNameWithReturnType(), and clang::insights::InsightsBase::InsertIndentedText().
The documentation for this class was generated from the following files:
CompilerGeneratedHandler.h
CompilerGeneratedHandler.cpp