C++ Insights: clang::insights::TemplateHandler Class Reference
clang::insights::TemplateHandler Class Reference final
Reveal the resulting code of an instantiated template.
#include "/__w/cppinsights/cppinsights/cppinsights/TemplateHandler.h"
Public Member Functions
TemplateHandler (Rewriter &rewrite, ast_matchers::MatchFinder &matcher)
void run (const ast_matchers::MatchFinder::MatchResult &result) override
Additional Inherited Members
Protected Member Functions inherited from clang::insights::InsightsBase
InsightsBase (Rewriter &rewriter)
void InsertIndentedText (SourceLocation loc, OutputFormatHelper &outputFormatHelper)
Protected Attributes inherited from clang::insights::InsightsBase
Rewriter & mRewrite
Detailed Description
Reveal the resulting code of an instantiated template.
Currently only template functions are supported. Classes are not generated fully. As placing the resulting code is not easy all generated functions are placed behind a ifdef INSIGHTS_USE_TEMPLATE.
Definition at line 24 of file TemplateHandler.h.
Constructor & Destructor Documentation
TemplateHandler()
clang::insights::TemplateHandler::TemplateHandler (Rewriter & rewrite, ast_matchers::MatchFinder & matcher)
Definition at line 97 of file TemplateHandler.cpp.
References clang::ast_matchers::conceptDecl, clang::ast_matchers::hasThisTUParent, clang::insights::idClass, clang::insights::idDecl, clang::insights::idFunc, clang::insights::idFunc2, clang::insights::idVar, clang::insights::idVarSpec, clang::ast_matchers::varTemplateDecl, and clang::ast_matchers::varTemplateSpecializationDecl.
Member Function Documentation
run()
void clang::insights::TemplateHandler::run (const ast_matchers::MatchFinder::MatchResult & result) override
Definition at line 153 of file TemplateHandler.cpp.
References clang::ast_matchers::conceptDecl, clang::insights::OutputFormatHelper::empty(), clang::insights::CoroutineBodyFinder::Find(), clang::insights::FindLocationAfterRBrace(), clang::insights::FindLocationAfterSemi(), clang::insights::GetSourceRangeAfterSemi(), clang::insights::idClass, clang::insights::idDecl, clang::insights::idFunc, clang::insights::idFunc2, clang::insights::idVar, clang::insights::idVarSpec, clang::insights::CodeGenerator::InsertArg(), clang::insights::InsightsBase::InsertIndentedText(), clang::insights::InsertInstantiatedTemplate(), clang::insights::CodeGenerator::InsertPrimaryTemplate(), clang::insights::IsMacroLocation(), clang::insights::InsightsBase::mRewrite, and RETURN_IF.
The documentation for this class was generated from the following files:
TemplateHandler.h
TemplateHandler.cpp