C++ Insights: clang::insights::CodeGenerator::LambdaHelper Class Reference
clang::insights::CodeGenerator::LambdaHelper Class Reference
#include "CodeGenerator.h"
Public Member Functions
LambdaHelper (const LambdaCallerType lambdaCallerType, OutputFormatHelper &outputFormatHelper)
void finish ()
OutputFormatHelper & buffer ()
std::string & inits ()
void insertInits (OutputFormatHelper &outputFormatHelper)
LambdaCallerType callerType () const
bool insertName () const
void setInsertName (bool b)
Additional Inherited Members
Public Attributes inherited from StackListEntry< LambdaHelper >
StackListEntry * next
StackListEntry * prev
Detailed Description
Definition at line 121 of file CodeGenerator.h.
Constructor & Destructor Documentation
LambdaHelper()
clang::insights::CodeGenerator::LambdaHelper::LambdaHelper (const LambdaCallerType lambdaCallerType, OutputFormatHelper & outputFormatHelper) inline
Definition at line 124 of file CodeGenerator.h.
References clang::insights::OutputFormatHelper::SetIndent().
Member Function Documentation
buffer()
OutputFormatHelper & clang::insights::CodeGenerator::LambdaHelper::buffer () inline
Definition at line 139 of file CodeGenerator.h.
Referenced by clang::insights::CodeGenerator::HandleLambdaExpr().
callerType()
LambdaCallerType clang::insights::CodeGenerator::LambdaHelper::callerType () const inline
Definition at line 151 of file CodeGenerator.h.
Referenced by clang::insights::CodeGenerator::InsideDecltype().
finish()
void clang::insights::CodeGenerator::LambdaHelper::finish () inline
Definition at line 132 of file CodeGenerator.h.
References clang::insights::OutputFormatHelper::empty(), and clang::insights::OutputFormatHelper::InsertAt().
inits()
std::string & clang::insights::CodeGenerator::LambdaHelper::inits () inline
Definition at line 141 of file CodeGenerator.h.
insertInits()
void clang::insights::CodeGenerator::LambdaHelper::insertInits (OutputFormatHelper & outputFormatHelper) inline
Definition at line 143 of file CodeGenerator.h.
References clang::insights::OutputFormatHelper::Append().
insertName()
bool clang::insights::CodeGenerator::LambdaHelper::insertName () const inline
Definition at line 152 of file CodeGenerator.h.
References clang::insights::CodeGenerator::Decltype.
setInsertName()
void clang::insights::CodeGenerator::LambdaHelper::setInsertName (bool b) inline
Definition at line 154 of file CodeGenerator.h.
The documentation for this class was generated from the following file:
CodeGenerator.h