C++ Insights: clang::insights::UsingCodeGenerator Class Reference
clang::insights::UsingCodeGenerator Class Reference final
Handle using statements which pull functions ore members from a base class into the class.
Public Member Functions
UsingCodeGenerator (OutputFormatHelper &_outputFormatHelper)
void InsertArg (const CXXMethodDecl *stmt) override
void InsertArg (const FieldDecl *stmt) override
void InsertArg (const CXXRecordDecl *) override
void InsertArg (const TypedefDecl *) override
virtual void InsertArg (const Decl *stmt)
virtual void InsertArg (const Stmt *stmt)
Public Member Functions inherited from clang::insights::CodeGenerator
constexpr CodeGenerator (OutputFormatHelper &_outputFormatHelper)
constexpr CodeGenerator (OutputFormatHelper &_outputFormatHelper, LambdaInInitCapture lambdaInitCapture)
constexpr CodeGenerator (OutputFormatHelper &_outputFormatHelper, LambdaStackType &lambdaStack)
virtual ~CodeGenerator ()=default
virtual void InsertArg (const Decl *stmt)
virtual void InsertArg (const Stmt *stmt)
template<typename T >
void InsertTemplateArgs (const T &t)
void InsertTemplateArgs (const ClassTemplateSpecializationDecl &clsTemplateSpe)
void InsertFunctionNameWithReturnType (const FunctionDecl &decl, const CXXConstructorDecl *cxxInheritedCtorDecl=nullptr)
Insert the code for a FunctionDecl.
template<typename T >
void InsertTemplateArgs (const ArrayRef< T > &array)
void InsertAttributes (const Decl::attr_range &)
void InsertAttribute (const Attr &)
Protected Member Functions
bool InsertNamespace () const override
Protected Member Functions inherited from clang::insights::CodeGenerator
STRONG_BOOL (LambdaInInitCapture)
constexpr CodeGenerator (OutputFormatHelper &_outputFormatHelper, LambdaStackType &lambdaStack, LambdaInInitCapture lambdaInitCapture)
virtual bool InsertVarDecl ()
virtual bool InsertComma ()
virtual bool InsertSemi ()
virtual bool ShowXValueCasts () const
Show casts to xvalues independent from the show all casts option.
void HandleTemplateParameterPack (const ArrayRef< TemplateArgument > &args)
void HandleCompoundStmt (const CompoundStmt *stmt)
void HandleLocalStaticNonTrivialClass (const VarDecl *stmt)
Show what is behind a local static variable.
void FormatCast (const std::string_view castName, const QualType &CastDestType, const Expr *SubExpr, const CastKind &castKind)
void ForEachArg (const auto &arguments, auto &&lambda)
void InsertArgWithParensIfNeeded (const Stmt *stmt)
void InsertSuffix (const QualType &type)
void InsertTemplateArg (const TemplateArgument &arg)
void InsertTemplateArg (const TemplateArgumentLoc &arg)
bool InsertLambdaStaticInvoker (const CXXMethodDecl *cxxMethodDecl)
void InsertTemplateParameters (const TemplateParameterList &list)
STRONG_BOOL (InsertInline)
void InsertConceptConstraint (const llvm::SmallVectorImpl< const Expr * > &constraints, const InsertInline insertInline)
void InsertConceptConstraint (const FunctionDecl *tmplDecl)
void InsertConceptConstraint (const VarDecl *varDecl)
void InsertConceptConstraint (const TemplateParameterList &tmplDecl)
void InsertQualifierAndNameWithTemplateArgs (const DeclarationName &declName, const auto *stmt)
void InsertQualifierAndName (const DeclarationName &declName, const NestedNameSpecifier *qualifier, const bool hasTemplateKeyword)
void InsertCXXMethodHeader (const CXXMethodDecl *stmt, OutputFormatHelper &initOutputFormatHelper)
void InsertTemplateGuardBegin (const FunctionDecl *stmt)
void InsertTemplateGuardEnd (const FunctionDecl *stmt)
void InsertTemplateSpecializationHeader ()
Insert template<> to introduce a template specialization.
void InsertNamespace (const NestedNameSpecifier *namespaceSpecifier)
void ParseDeclContext (const DeclContext *Ctx)
STRONG_BOOL (SkipBody)
void InsertCXXMethodDecl (const CXXMethodDecl *stmt, SkipBody skipBody)
template<typename T >
void InsertConstructorExpr (const T *stmt)
Generalized function to insert either a CXXConstructExpr or CXXUnresolvedConstructExpr.
void InsertCurlysIfRequired (const Stmt *stmt)
Check whether or not this statement will add curlys or parentheses and add them only if required.
void InsertIfOrSwitchInitVariables (same_as_any_of< const IfStmt, const SwitchStmt > auto *stmt)
STRONG_BOOL (AddNewLineAfter)
void WrapInCompoundIfNeeded (const Stmt *stmt, const AddNewLineAfter addNewLineAfter)
STRONG_BOOL (AddSpaceAtTheEnd)
void WrapInParens (void_func_ref lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
void WrapInParensIfNeeded (bool needsParens, void_func_ref lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
void WrapInCurliesIfNeeded (bool needsParens, void_func_ref lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
void WrapInCurlys (void_func_ref lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
void WrapInParensOrCurlys (const BraceKind curlys, void_func_ref lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
void UpdateCurrentPos ()
void HandleLambdaExpr (const LambdaExpr *stmt, LambdaHelper &lambdaHelper)
STRONG_BOOL (SkipVarDecl)
STRONG_BOOL (UseCommaInsteadOfSemi)
STRONG_BOOL (NoEmptyInitList)
STRONG_BOOL (ShowConstantExprValue)
Additional Inherited Members
Static Public Member Functions inherited from clang::insights::CodeGenerator
static bool NeedToInsertNewHeader ()
static bool NeedToInsertExceptionHeader ()
Track whether we have a noexcept transformation which needs the exception header.
static bool NeedToInsertUtilityHeader ()
Track whether we inserted a std::move due, to a static transformation, this means we need the utility header.
Protected Types inherited from clang::insights::CodeGenerator
enum class LambdaCallerType {
VarDecl , InitCapture , CallExpr , OperatorCallExpr ,
MemberCallExpr , LambdaExpr , ReturnStmt , BinaryOperator ,
CXXMethodDecl
}
enum class BraceKind { Parens , Curlys }
using LambdaStackType = StackList< class LambdaHelper >
Static Protected Member Functions inherited from clang::insights::CodeGenerator
static std::string_view GetBuiltinTypeSuffix (const BuiltinType::Kind &kind)
static std::string FillConstantArray (const ConstantArrayType *ct, const std::string &value, const uint64_t startAt)
static std::string GetValueOfValueInit (const QualType &t)
Protected Attributes inherited from clang::insights::CodeGenerator
OutputFormatHelper & mOutputFormatHelper
LambdaStackType mLambdaStackThis {}
LambdaStackType & mLambdaStack
LambdaInInitCapture mLambdaInitCapture {LambdaInInitCapture::No}
ShowConstantExprValue mShowConstantExprValue {ShowConstantExprValue::No}
SkipVarDecl mSkipVarDecl {SkipVarDecl::No}
UseCommaInsteadOfSemi mUseCommaInsteadOfSemi {UseCommaInsteadOfSemi::No}
NoEmptyInitList mNoEmptyInitList
At least in case if a requires-clause containing T{} we don't want to get T{{}}.
const LambdaExpr * mLambdaExpr {}
llvm::Optional< size_t > mCurrentPos {}
llvm::Optional< size_t > mCurrentReturnPos {}
llvm::Optional< size_t > mCurrentFieldPos {}
OutputFormatHelper * mOutputFormatHelperOutside
Helper output buffer for std::initializer_list expansion.
bool mRequiresImplicitReturnZero {}
Track whether this is a function with an imlpicit return 0.
Static Protected Attributes inherited from clang::insights::CodeGenerator
static bool mHaveLocalStatic
Track whether there was a thread-safe static in the code.
static bool mHaveMovedLambda
Track whether there was a std::move inserted.
static bool mHaveException
Track whether there was a noexcept transformation requireing the exception header.
static constexpr auto MAX_FILL_VALUES_FOR_ARRAYS
Detailed Description
Handle using statements which pull functions ore members from a base class into the class.
Definition at line 124 of file CodeGenerator.cpp.
Constructor & Destructor Documentation
UsingCodeGenerator()
clang::insights::UsingCodeGenerator::UsingCodeGenerator (OutputFormatHelper & _outputFormatHelper) inline
Definition at line 127 of file CodeGenerator.cpp.
Member Function Documentation
InsertArg() [1/6]
void clang::insights::UsingCodeGenerator::InsertArg (const CXXMethodDecl * stmt) inline override
Definition at line 133 of file CodeGenerator.cpp.
References clang::insights::OutputFormatHelper::Append(), clang::insights::CodeGenerator::InsertCXXMethodDecl(), kwCppCommentStartSpace, and clang::insights::CodeGenerator::mOutputFormatHelper.
InsertArg() [2/6]
void clang::insights::UsingCodeGenerator::InsertArg (const CXXRecordDecl *) inline override
Definition at line 147 of file CodeGenerator.cpp.
InsertArg() [3/6]
void clang::insights::CodeGenerator::InsertArg
Definition at line 131 of file CodeGenerator.cpp.
InsertArg() [4/6]
void clang::insights::UsingCodeGenerator::InsertArg (const FieldDecl * stmt) inline override
Definition at line 140 of file CodeGenerator.cpp.
References clang::insights::OutputFormatHelper::Append(), clang::insights::CodeGenerator::InsertArg(), kwCppCommentStartSpace, and clang::insights::CodeGenerator::mOutputFormatHelper.
InsertArg() [5/6]
void clang::insights::CodeGenerator::InsertArg
Definition at line 132 of file CodeGenerator.cpp.
InsertArg() [6/6]
void clang::insights::UsingCodeGenerator::InsertArg (const TypedefDecl *) inline override
Definition at line 150 of file CodeGenerator.cpp.
InsertNamespace()
bool clang::insights::UsingCodeGenerator::InsertNamespace () const inline override protected virtual
Reimplemented from clang::insights::CodeGenerator.
Definition at line 153 of file CodeGenerator.cpp.
The documentation for this class was generated from the following file:
CodeGenerator.cpp