C++ Insights: clang::insights::LifetimeTracker Class Reference
clang::insights::LifetimeTracker Class Reference
#include "CodeGenerator.h"
Public Member Functions
void Add (const VarDecl *decl)
void AddExtended (const VarDecl *decl, const ValueDecl *extending)
LifetimeEntry & top ()
void removeTop ()
void StartScope (bool funcStart)
bool Return (OutputFormatHelper &ofm)
bool EndScope (OutputFormatHelper &ofm, bool clear)
Detailed Description
Definition at line 66 of file CodeGenerator.h.
Member Function Documentation
Add()
void clang::insights::LifetimeTracker::Add (const VarDecl * decl)
Definition at line 45 of file LifetimeTracker.cpp.
References GetInsightsOptions(), and RETURN_IF.
Referenced by clang::insights::CodeGenerator::InsertMethodBody().
AddExtended()
void clang::insights::LifetimeTracker::AddExtended (const VarDecl * decl, const ValueDecl * extending)
Definition at line 34 of file LifetimeTracker.cpp.
Referenced by clang::insights::CodeGenerator::LifetimeAddExtended().
EndScope()
bool clang::insights::LifetimeTracker::EndScope (OutputFormatHelper & ofm, bool clear)
Definition at line 142 of file LifetimeTracker.cpp.
References GetInsightsOptions(), removeTop(), and RETURN_FALSE_IF.
Referenced by clang::insights::CodeGenerator::EndLifetimeScope().
removeTop()
void clang::insights::LifetimeTracker::removeTop ()
Definition at line 131 of file LifetimeTracker.cpp.
References clang::insights::LifetimeEntry::scope.
Referenced by EndScope().
Return()
bool clang::insights::LifetimeTracker::Return (OutputFormatHelper & ofm)
Definition at line 103 of file LifetimeTracker.cpp.
References GetInsightsOptions(), clang::insights::asthelpers::mkNullStmt(), and RETURN_FALSE_IF.
StartScope()
void clang::insights::LifetimeTracker::StartScope (bool funcStart)
Definition at line 23 of file LifetimeTracker.cpp.
References GetInsightsOptions(), and RETURN_IF.
Referenced by clang::insights::CodeGenerator::StartLifetimeScope().
top()
LifetimeEntry & clang::insights::LifetimeTracker::top () inline
Definition at line 78 of file CodeGenerator.h.
The documentation for this class was generated from the following files:
CodeGenerator.h
LifetimeTracker.cpp