C++ Insights: CppInsightASTConsumer Class Reference
CppInsightASTConsumer Class Reference final
Public Member Functions
CppInsightASTConsumer (Rewriter &rewriter)
void HandleTranslationUnit (ASTContext &context) override
Detailed Description
Definition at line 113 of file Insights.cpp.
Constructor & Destructor Documentation
CppInsightASTConsumer()
CppInsightASTConsumer::CppInsightASTConsumer (Rewriter & rewriter) inline explicit
Definition at line 116 of file Insights.cpp.
References GetInsightsOptions(), and gInsightsOptions.
Member Function Documentation
HandleTranslationUnit()
void CppInsightASTConsumer::HandleTranslationUnit (ASTContext & context) inline override
Definition at line 134 of file Insights.cpp.
References cxaStart, clang::insights::EmitGlobalVariableCtors(), gAST, GetInsightsOptions(), and clang::insights::gGlobalInserts.
The documentation for this class was generated from the following file:
Insights.cpp