C++Insights: clang::insights::AutoStmtHandler Class Reference
clang::insights::AutoStmtHandler Class Reference final
Show the types behind auto.
#include "/home/builder/AutoStmtHandler.h"
Public Member Functions
AutoStmtHandler (Rewriter &rewrite, ast_matchers::MatchFinder &matcher)
void run (const ast_matchers::MatchFinder::MatchResult &result) override
Additional Inherited Members
Protected Member Functions inherited from clang::insights::InsightsBase
InsightsBase (Rewriter &rewriter)
void InsertIndentedText (SourceLocation loc, OutputFormatHelper &outputFormatHelper)
Protected Attributes inherited from clang::insights::InsightsBase
Rewriter & mRewrite
Detailed Description
Show the types behind auto.
The AutoStmtHandler matches all auto statements in global space. That means:
auto i = 0;
auto [x,y] = Point{1,2};
auto lambda = [&]() { return errno; };
The transformation itself shows the fully expanded type behind auto and a possible associated statmente like lambda or structured binding. For example:
auto i = 0;
will give you
int i = 0;
Definition at line 39 of file AutoStmtHandler.h.
Constructor & Destructor Documentation
AutoStmtHandler()
clang::insights::AutoStmtHandler::AutoStmtHandler (Rewriter & rewrite, ast_matchers::MatchFinder & matcher)
Definition at line 30 of file AutoStmtHandler.cpp.
References clang::ast_matchers::isAutoAncestor, clang::ast_matchers::isTemplate, clang::ast_matchers::myDecltypeType, and clang::ast_matchers::varTemplateDecl.
Member Function Documentation
run()
void clang::insights::AutoStmtHandler::run (const ast_matchers::MatchFinder::MatchResult & result) override
Definition at line 51 of file AutoStmtHandler.cpp.
References clang::insights::GetBeginLoc(), clang::insights::GetSM(), clang::insights::GetSourceRangeAfterSemi(), clang::insights::CodeGenerator::InsertArg(), and clang::insights::InsightsBase::mRewrite.
The documentation for this class was generated from the following files:
AutoStmtHandler.h
AutoStmtHandler.cpp