C++Insights: clang::insights::LambdaInitCaptureCodeGenerator Class Reference
clang::insights::LambdaInitCaptureCodeGenerator Class Reference final
A special code generator for Lambda init captures which use std::move.
Public Member Functions
LambdaInitCaptureCodeGenerator (OutputFormatHelper &outputFormatHelper, LambdaStackType &lambdaStack, std::string &varName)
void InsertArg (const DeclRefExpr *stmt) override
Public Member Functions inherited from clang::insights::CodeGenerator
CodeGenerator (OutputFormatHelper &_outputFormatHelper)
CodeGenerator (OutputFormatHelper &_outputFormatHelper, LambdaStackType &lambdaStack)
virtual ~CodeGenerator ()=default
virtual void InsertArg (const Decl *stmt)
virtual void InsertArg (const Stmt *stmt)
template<typename T >
auto InsertTemplateArgs (const T &t) -> decltype((void) t.template_arguments(), void())
template<typename T >
auto InsertTemplateArgs (const T &t) -> decltype((void) t.asArray(), void())
void InsertTemplateArgs (const ClassTemplateSpecializationDecl &clsTemplateSpe)
void InsertTemplateArgs (const FunctionDecl &FD)
STRONG_BOOL (SkipAccess)
void InsertAccessModifierAndNameWithReturnType (const FunctionDecl &decl, const SkipAccess skipAccess=SkipAccess::No, const CXXConstructorDecl *cxxInheritedCtorDecl=nullptr)
Insert the code for a FunctionDecl.
template<typename T >
void InsertTemplateArgs (const ArrayRef< T > &array)
void InsertAttributes (const Decl::attr_range &)
void InsertAttribute (const Attr &)
Additional Inherited Members
Static Public Member Functions inherited from clang::insights::CodeGenerator
static bool NeedToInsertNewHeader ()
Protected Types inherited from clang::insights::CodeGenerator
enum LambdaCallerType {
LambdaCallerType::VarDecl, LambdaCallerType::CallExpr, LambdaCallerType::OperatorCallExpr, LambdaCallerType::MemberCallExpr,
LambdaCallerType::LambdaExpr, LambdaCallerType::ReturnStmt, LambdaCallerType::BinaryOperator, LambdaCallerType::CXXMethodDecl
}
enum BraceKind { BraceKind::Parens, BraceKind::Curlys }
using LambdaStackType = StackList< class LambdaHelper >
Protected Member Functions inherited from clang::insights::CodeGenerator
virtual bool InsertVarDecl ()
virtual bool InsertComma ()
virtual bool InsertSemi ()
virtual bool InsertNamespace () const
void HandleTemplateParameterPack (const ArrayRef< TemplateArgument > &args)
void HandleCompoundStmt (const CompoundStmt *stmt)
void HandleLocalStaticNonTrivialClass (const VarDecl *stmt)
Show what is behind a local static variable.
void FormatCast (const std::string castName, const QualType &CastDestType, const Expr *SubExpr, const CastKind &castKind)
template<typename T , typename Lambda >
void ForEachArg (const T &arguments, Lambda &&lambda)
void InsertArgWithParensIfNeeded (const Stmt *stmt)
void InsertSuffix (const QualType &type)
void InsertTemplateArg (const TemplateArgument &arg)
void InsertTemplateArg (const TemplateArgumentLoc &arg)
bool InsertLambdaStaticInvoker (const CXXMethodDecl *cxxMethodDecl)
void InsertTemplateParameters (const TemplateParameterList &list)
template<typename T >
void InsertQualifierAndNameWithTemplateArgs (const DeclarationName &declName, const T *stmt)
void InsertQualifierAndName (const DeclarationName &declName, const NestedNameSpecifier *qualifier, const bool hasTemplateKeyword)
void InsertCXXMethodHeader (const CXXMethodDecl *stmt, OutputFormatHelper &initOutputFormatHelper)
void InsertTemplateGuardBegin (const FunctionDecl *stmt)
void InsertTemplateGuardEnd (const FunctionDecl *stmt)
void InsertTemplateSpecializationHeader ()
Insert template<> to introduce a template specialization.
void InsertNamespace (const NestedNameSpecifier *namespaceSpecifier)
void ParseDeclContext (const DeclContext *Ctx)
STRONG_BOOL (SkipBody)
void InsertCXXMethodDecl (const CXXMethodDecl *stmt, SkipBody skipBody)
void InsertCurlysIfRequired (const Stmt *stmt)
Check whether or not this statement will add curlys or parentheses and add them only if required.
STRONG_BOOL (AddSpaceAtTheEnd)
template<typename T >
void WrapInParens (T &&lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
template<typename T >
void WrapInParensIfNeeded (bool needsParens, T &&lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
template<typename T >
void WrapInCurliesIfNeeded (bool needsParens, T &&lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
template<typename T >
void WrapInCurlys (T &&lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
template<typename T >
void WrapInParensOrCurlys (const BraceKind curlys, T &&lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
void UpdateCurrentPos ()
void HandleLambdaExpr (const LambdaExpr *stmt, LambdaHelper &lambdaHelper)
STRONG_BOOL (SkipVarDecl)
STRONG_BOOL (UseCommaInsteadOfSemi)
Static Protected Member Functions inherited from clang::insights::CodeGenerator
static const char * GetKind (const UnaryExprOrTypeTraitExpr &uk)
static const char * GetBuiltinTypeSuffix (const BuiltinType::Kind &kind)
static std::string FillConstantArray (const ConstantArrayType *ct, const std::string &value, const uint64_t startAt)
static std::string GetValueOfValueInit (const QualType &t)
Protected Attributes inherited from clang::insights::CodeGenerator
OutputFormatHelper & mOutputFormatHelper
LambdaStackType mLambdaStackThis
LambdaStackType & mLambdaStack
SkipVarDecl mSkipVarDecl
UseCommaInsteadOfSemi mUseCommaInsteadOfSemi
const LambdaExpr * mLambdaExpr
llvm::Optional< size_t > mCurrentPos {}
llvm::Optional< size_t > mCurrentReturnPos {}
llvm::Optional< size_t > mCurrentFieldPos {}
OutputFormatHelper * mOutputFormatHelperOutside
Helper output buffer for std::initializer_list expansion.
Static Protected Attributes inherited from clang::insights::CodeGenerator
static bool mHaveLocalStatic
static constexpr auto MAX_FILL_VALUES_FOR_ARRAYS
Detailed Description
A special code generator for Lambda init captures which use std::move.
Definition at line 157 of file CodeGenerator.cpp.
Constructor & Destructor Documentation
LambdaInitCaptureCodeGenerator()
clang::insights::LambdaInitCaptureCodeGenerator::LambdaInitCaptureCodeGenerator (OutputFormatHelper & outputFormatHelper, LambdaStackType & lambdaStack, std::string & varName) inline explicit
Definition at line 160 of file CodeGenerator.cpp.
References clang::insights::CodeGenerator::InsertArg().
Member Function Documentation
InsertArg()
void clang::insights::LambdaInitCaptureCodeGenerator::InsertArg (const DeclRefExpr * stmt) inline override
Replace every VarDecl with the given variable name. This cover init captures which introduce a new name. However, it means that all VarDecl's will be changed. TODO: Check if it is really good to replace all VarDecl's
Definition at line 173 of file CodeGenerator.cpp.
References clang::insights::OutputFormatHelper::Append(), clang::insights::CodeGenerator::InsertArg(), and clang::insights::CodeGenerator::mOutputFormatHelper.
The documentation for this class was generated from the following file:
CodeGenerator.cpp