C++ Insights: clang::insights::ContinueASTTransformer Class Reference
clang::insights::ContinueASTTransformer Class Reference
Public Member Functions
ContinueASTTransformer (Stmt *stmt, std::string_view continueLabel)
void Visit (Stmt *stmt)
void VisitContinueStmt (ContinueStmt *stmt)
void VisitStmt (Stmt *stmt)
Public Attributes
bool found {}
Detailed Description
Definition at line 2559 of file CodeGenerator.cpp.
Constructor & Destructor Documentation
ContinueASTTransformer()
clang::insights::ContinueASTTransformer::ContinueASTTransformer (Stmt * stmt, std::string_view continueLabel) inline
Definition at line 2567 of file CodeGenerator.cpp.
References Visit().
Member Function Documentation
Visit()
void clang::insights::ContinueASTTransformer::Visit (Stmt * stmt) inline
Definition at line 2574 of file CodeGenerator.cpp.
Referenced by ContinueASTTransformer(), and VisitStmt().
VisitContinueStmt()
void clang::insights::ContinueASTTransformer::VisitContinueStmt (ContinueStmt * stmt) inline
Definition at line 2581 of file CodeGenerator.cpp.
References found, clang::insights::asthelpers::Goto(), and clang::insights::asthelpers::ReplaceNode().
VisitStmt()
void clang::insights::ContinueASTTransformer::VisitStmt (Stmt * stmt) inline
Definition at line 2588 of file CodeGenerator.cpp.
References Visit().
Member Data Documentation
found
bool clang::insights::ContinueASTTransformer::found {}
Definition at line 2565 of file CodeGenerator.cpp.
Referenced by VisitContinueStmt().
The documentation for this class was generated from the following file:
CodeGenerator.cpp