C++ Insights: clang::insights::FunctionDeclHandler Class Reference
clang::insights::FunctionDeclHandler Class Reference final
Match function decls.
#include "/__w/cppinsights/cppinsights/cppinsights/FunctionDeclHandler.h"
Public Member Functions
FunctionDeclHandler (Rewriter &rewrite, ast_matchers::MatchFinder &matcher)
void run (const ast_matchers::MatchFinder::MatchResult &result) override
Additional Inherited Members
Protected Member Functions inherited from clang::insights::InsightsBase
InsightsBase (Rewriter &rewriter)
void InsertIndentedText (SourceLocation loc, OutputFormatHelper &outputFormatHelper)
Protected Attributes inherited from clang::insights::InsightsBase
Rewriter & mRewrite
Detailed Description
Match function decls.
To get a broader rewrite of statements match the entire function and rewrite it.
Definition at line 23 of file FunctionDeclHandler.h.
Constructor & Destructor Documentation
FunctionDeclHandler()
clang::insights::FunctionDeclHandler::FunctionDeclHandler (Rewriter & rewrite, ast_matchers::MatchFinder & matcher)
Definition at line 77 of file FunctionDeclHandler.cpp.
References clang::ast_matchers::hasThisTUParent, clang::insights::idFunc, and clang::ast_matchers::isTemplate.
Member Function Documentation
run()
void clang::insights::FunctionDeclHandler::run (const ast_matchers::MatchFinder::MatchResult & result) override
Definition at line 86 of file FunctionDeclHandler.cpp.
References clang::insights::findTrailingReturnTypeSourceLocation(), clang::insights::GetLangOpts(), clang::insights::GetSM(), clang::insights::GetSourceRangeAfterSemi(), clang::insights::idFunc, clang::insights::CodeGenerator::InsertArg(), and clang::insights::InsightsBase::mRewrite.
The documentation for this class was generated from the following files:
FunctionDeclHandler.h
FunctionDeclHandler.cpp