C++ Insights: clang::insights::TemporaryDeclFinder Class Reference
clang::insights::TemporaryDeclFinder Class Reference
Find a DeclRefExpr belonging to a DecompositionDecl.
Public Member Functions
TemporaryDeclFinder (CodeGenerator &_codeGenerator, const Stmt *stmt, bool inspectReturn=false)
~TemporaryDeclFinder ()
bool Found () const
std::string Name () const
void VisitCXXTemporaryObjectExpr (CXXTemporaryObjectExpr *expr)
void VisitMaterializeTemporaryExpr (MaterializeTemporaryExpr *stmt)
void VisitStmt (Stmt *stmt)
void Visit (Stmt *stmt)
Detailed Description
Find a DeclRefExpr belonging to a DecompositionDecl.
Definition at line 929 of file CodeGenerator.cpp.
Constructor & Destructor Documentation
TemporaryDeclFinder()
clang::insights::TemporaryDeclFinder::TemporaryDeclFinder (CodeGenerator & _codeGenerator, const Stmt * stmt, bool inspectReturn = false) inline
Definition at line 939 of file CodeGenerator.cpp.
References clang::insights::asthelpers::Function(), GetGlobalAST(), GetInsightsOptions(), clang::insights::GetTemporaryName(), clang::insights::CodeGenerator::InsertArg(), RETURN_IF, clang::insights::asthelpers::Variable(), and clang::insights::asthelpers::VoidTy().
~TemporaryDeclFinder()
clang::insights::TemporaryDeclFinder::~TemporaryDeclFinder () inline
Definition at line 986 of file CodeGenerator.cpp.
References clang::insights::CodeGenerator::EndLifetimeScope().
Member Function Documentation
Found()
bool clang::insights::TemporaryDeclFinder::Found () const inline
Definition at line 993 of file CodeGenerator.cpp.
Name()
std::string clang::insights::TemporaryDeclFinder::Name () const inline
Definition at line 995 of file CodeGenerator.cpp.
Visit()
void clang::insights::TemporaryDeclFinder::Visit (Stmt * stmt) inline
Definition at line 1079 of file CodeGenerator.cpp.
VisitCXXTemporaryObjectExpr()
void clang::insights::TemporaryDeclFinder::VisitCXXTemporaryObjectExpr (CXXTemporaryObjectExpr * expr) inline
Definition at line 997 of file CodeGenerator.cpp.
References GetGlobalAST(), GetInsightsOptions(), clang::insights::GetName(), clang::insights::asthelpers::mkDeclRefExpr(), clang::insights::asthelpers::ReplaceNode(), and clang::insights::asthelpers::Variable().
VisitMaterializeTemporaryExpr()
void clang::insights::TemporaryDeclFinder::VisitMaterializeTemporaryExpr (MaterializeTemporaryExpr * stmt) inline
Definition at line 1045 of file CodeGenerator.cpp.
References clang::insights::GetTemporaryName(), clang::insights::CodeGenerator::LifetimeAddExtended(), clang::insights::asthelpers::mkDeclRefExpr(), clang::insights::asthelpers::ReplaceNode(), RETURN_IF, clang::insights::CodeGenerator::StartLifetimeScope(), and clang::insights::asthelpers::Variable().
VisitStmt()
void clang::insights::TemporaryDeclFinder::VisitStmt (Stmt * stmt) inline
Definition at line 1067 of file CodeGenerator.cpp.
The documentation for this class was generated from the following file:
CodeGenerator.cpp