C++ Insights: clang::insights::InsightsBase Class Reference
clang::insights::InsightsBase Class Reference
#include "/__w/cppinsights/cppinsights/cppinsights/InsightsBase.h"
Protected Member Functions
InsightsBase (Rewriter &rewriter)
void InsertIndentedText (SourceLocation loc, OutputFormatHelper &outputFormatHelper)
Protected Attributes
Rewriter & mRewrite
Detailed Description
Definition at line 26 of file InsightsBase.h.
Constructor & Destructor Documentation
InsightsBase()
clang::insights::InsightsBase::InsightsBase (Rewriter & rewriter) inline explicit protected
Definition at line 31 of file InsightsBase.h.
Member Function Documentation
InsertIndentedText()
void clang::insights::InsightsBase::InsertIndentedText (SourceLocation loc, OutputFormatHelper & outputFormatHelper) protected
Definition at line 16 of file InsightsBase.cpp.
References clang::insights::OutputFormatHelper::GetString(), and mRewrite.
Referenced by clang::insights::RecordDeclHandler::run(), and clang::insights::TemplateHandler::run().
Member Data Documentation
mRewrite
Rewriter& clang::insights::InsightsBase::mRewrite protected
Definition at line 29 of file InsightsBase.h.
Referenced by InsertIndentedText(), clang::insights::FunctionDeclHandler::run(), clang::insights::GlobalVariableHandler::run(), clang::insights::RecordDeclHandler::run(), clang::insights::StaticAssertHandler::run(), and clang::insights::TemplateHandler::run().
The documentation for this class was generated from the following files:
InsightsBase.h
InsightsBase.cpp