C++Insights: clang::insights::ScopeHandler Class Reference
clang::insights::ScopeHandler Class Reference
The ScopeHandler tracks the current scope.
#include "/home/builder/InsightsHelpers.h"
Public Member Functions
ScopeHandler (const Decl *d)
~ScopeHandler ()
Static Public Member Functions
static std::string RemoveCurrentScope (std::string name)
Remove the current scope from a string.
Detailed Description
The ScopeHandler tracks the current scope.
The ScopeHandler tracks the current scope, knows about all the parts and is able to remove the current scope part from a name.
Definition at line 234 of file InsightsHelpers.h.
Constructor & Destructor Documentation
ScopeHandler()
clang::insights::ScopeHandler::ScopeHandler (const Decl * d)
Definition at line 22 of file InsightsHelpers.cpp.
References clang::insights::GetName(), and StackList< T >::push().
~ScopeHandler()
clang::insights::ScopeHandler::~ScopeHandler ()
Definition at line 48 of file InsightsHelpers.cpp.
References StackList< T >::pop().
Member Function Documentation
RemoveCurrentScope()
std::string clang::insights::ScopeHandler::RemoveCurrentScope (std::string name) static
Remove the current scope from a string.
The default is that the entire scope is replaced. Suppose we are currently in N::X and having a symbol N::X::y then N::X:: is removed. However, there is a special case, where the last item is skipped.
Definition at line 55 of file InsightsHelpers.cpp.
References StackList< T >::back().
Referenced by clang::insights::CodeGenerator::FillConstantArray(), clang::insights::GetDeclContext(), clang::insights::details::GetName(), clang::insights::GetName(), clang::insights::GetNameAsWritten(), clang::insights::GetPlainName(), clang::insights::details::GetQualifiedName(), clang::insights::CodeGenerator::InsertNamespace(), and clang::insights::InsertQualifierAndName().
The documentation for this class was generated from the following files:
InsightsHelpers.h
InsightsHelpers.cpp