C++ Insights: clang::insights::CoroutinesCodeGenerator Class Reference
clang::insights::CoroutinesCodeGenerator Class Reference final
A special generator for coroutines. It is only activated, if -show-coroutines-transformation is given as a command line option.
#include "CodeGenerator.h"
Public Member Functions
CoroutinesCodeGenerator (OutputFormatHelper &_outputFormatHelper, const size_t posBeforeFunc)
CoroutinesCodeGenerator (OutputFormatHelper &_outputFormatHelper, const size_t posBeforeFunc, std::string_view fsmName, size_t suspendsCount, CoroutineASTData data)
~CoroutinesCodeGenerator () override
void InsertArg (const ImplicitCastExpr *stmt) override
void InsertArg (const CallExpr *stmt) override
void InsertArg (const CXXRecordDecl *stmt) override
void InsertArg (const OpaqueValueExpr *stmt) override
void InsertArg (const CoroutineBodyStmt *stmt) override
void InsertArg (const CoroutineSuspendExpr *stmt) override
void InsertArg (const CoreturnStmt *stmt) override
void InsertCoroutine (const FunctionDecl &fd, const CoroutineBodyStmt *body)
std::string GetFrameName () const
virtual void InsertArg (const Decl *stmt)
virtual void InsertArg (const Stmt *stmt)
Public Member Functions inherited from clang::insights::CodeGenerator
constexpr CodeGenerator (OutputFormatHelper &_outputFormatHelper)
constexpr CodeGenerator (OutputFormatHelper &_outputFormatHelper, LambdaInInitCapture lambdaInitCapture)
constexpr CodeGenerator (OutputFormatHelper &_outputFormatHelper, LambdaStackType &lambdaStack, ProcessingPrimaryTemplate processingPrimaryTemplate)
virtual ~CodeGenerator ()=default
template<typename T >
void InsertTemplateArgs (const T &t)
void InsertTemplateArgs (const ClassTemplateSpecializationDecl &clsTemplateSpe)
void InsertFunctionNameWithReturnType (const FunctionDecl &decl, const CXXConstructorDecl *cxxInheritedCtorDecl=nullptr)
Insert the code for a FunctionDecl.
template<typename T >
void InsertTemplateArgs (const ArrayRef< T > &array)
void InsertAttributes (const Decl *)
void InsertAttributes (const Decl::attr_range &)
void InsertAttribute (const Attr &)
void InsertTemplateArg (const TemplateArgument &arg)
STRONG_BOOL (TemplateParamsOnly)
void InsertTemplateParameters (const TemplateParameterList &list, const TemplateParamsOnly templateParamsOnly=TemplateParamsOnly::No)
! Skip template, type constraints and class/typename.
void StartLifetimeScope ()
void LifetimeAddExtended (const VarDecl *, const ValueDecl *)
void EndLifetimeScope ()
Protected Member Functions
bool InsertVarDecl (const VarDecl *vd) override
bool SkipSpaceAfterVarDecl () override
Protected Member Functions inherited from clang::insights::CodeGenerator
STRONG_BOOL (LambdaInInitCapture)
STRONG_BOOL (ProcessingPrimaryTemplate)
constexpr CodeGenerator (OutputFormatHelper &_outputFormatHelper, LambdaStackType &lambdaStack, LambdaInInitCapture lambdaInitCapture, ProcessingPrimaryTemplate processingPrimaryTemplate)
! We do not want to transform a primary template which contains a Coroutine.
virtual bool InsertComma ()
virtual bool InsertSemi ()
virtual bool InsertNamespace () const
virtual bool ShowXValueCasts () const
Show casts to xvalues independent from the show all casts option.
void HandleTemplateParameterPack (const ArrayRef< TemplateArgument > &args)
void HandleCompoundStmt (const CompoundStmt *stmt)
void HandleLocalStaticNonTrivialClass (const VarDecl *stmt)
Show what is behind a local static variable.
virtual void FormatCast (const std::string_view castName, const QualType &CastDestType, const Expr *SubExpr, const CastKind &castKind)
void ForEachArg (const auto &arguments, auto &&lambda)
void InsertArgWithParensIfNeeded (const Stmt *stmt)
void InsertSuffix (const QualType &type)
void InsertTemplateArg (const TemplateArgumentLoc &arg)
bool InsertLambdaStaticInvoker (const CXXMethodDecl *cxxMethodDecl)
STRONG_BOOL (InsertInline)
void InsertConceptConstraint (const llvm::SmallVectorImpl< const Expr * > &constraints, const InsertInline insertInline)
void InsertConceptConstraint (const FunctionDecl *tmplDecl)
void InsertConceptConstraint (const VarDecl *varDecl)
void InsertConceptConstraint (const TemplateParameterList &tmplDecl)
void InsertTemplate (const FunctionTemplateDecl *, bool withSpec)
void InsertQualifierAndNameWithTemplateArgs (const DeclarationName &declName, const auto *stmt)
void InsertQualifierAndName (const DeclarationName &declName, const NestedNameSpecifier *qualifier, const bool hasTemplateKeyword)
void InsertCXXMethodHeader (const CXXMethodDecl *stmt, OutputFormatHelper &initOutputFormatHelper)
void InsertTemplateGuardBegin (const FunctionDecl *stmt)
void InsertTemplateGuardEnd (const FunctionDecl *stmt)
void InsertTemplateSpecializationHeader (const Decl &)
Insert template<> to introduce a template specialization.
void InsertTemplateArgsObjectParam (const ArrayRef< TemplateArgument > &array)
void InsertTemplateArgsObjectParam (const TemplateParamObjectDecl &param)
void InsertNamespace (const NestedNameSpecifier *namespaceSpecifier)
void ParseDeclContext (const DeclContext *Ctx)
STRONG_BOOL (SkipBody)
virtual void InsertCXXMethodDecl (const CXXMethodDecl *stmt, SkipBody skipBody)
void InsertMethodBody (const FunctionDecl *stmt, const size_t posBeforeFunc)
template<typename T >
void InsertConstructorExpr (const T *stmt)
Generalized function to insert either a CXXConstructExpr or CXXUnresolvedConstructExpr.
void InsertCurlysIfRequired (const Stmt *stmt)
Check whether or not this statement will add curlys or parentheses and add them only if required.
void InsertIfOrSwitchInitVariables (same_as_any_of< const IfStmt, const SwitchStmt > auto *stmt)
void InsertInstantiationPoint (const SourceManager &sm, const SourceLocation &instLoc, std::string_view text={})
Inserts the instantiation point of a template.
STRONG_BOOL (AddNewLineAfter)
void WrapInCompoundIfNeeded (const Stmt *stmt, const AddNewLineAfter addNewLineAfter)
STRONG_BOOL (AddSpaceAtTheEnd)
void WrapInParens (void_func_ref lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
void WrapInParensIfNeeded (bool needsParens, void_func_ref lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
void WrapInCurliesIfNeeded (bool needsParens, void_func_ref lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
void WrapInCurlys (void_func_ref lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
void WrapInParensOrCurlys (const BraceKind curlys, void_func_ref lambda, const AddSpaceAtTheEnd addSpaceAtTheEnd=AddSpaceAtTheEnd::No)
void UpdateCurrentPos (std::optional< size_t > &pos)
void HandleLambdaExpr (const LambdaExpr *stmt, LambdaHelper &lambdaHelper)
bool InsideDecltype () const
STRONG_BOOL (SkipVarDecl)
STRONG_BOOL (UseCommaInsteadOfSemi)
STRONG_BOOL (NoEmptyInitList)
STRONG_BOOL (ShowConstantExprValue)
Additional Inherited Members
Public Attributes inherited from clang::insights::CodeGenerator
const Decl * mLastDecl {}
Protected Types inherited from clang::insights::CodeGenerator
enum class LambdaCallerType {
VarDecl , InitCapture , CallExpr , OperatorCallExpr ,
MemberCallExpr , LambdaExpr , ReturnStmt , BinaryOperator ,
CXXMethodDecl , TemplateHead , Decltype
}
enum class BraceKind { Parens , Curlys }
using LambdaStackType = StackList< class LambdaHelper >
Static Protected Member Functions inherited from clang::insights::CodeGenerator
static std::string_view GetBuiltinTypeSuffix (const BuiltinType::Kind &kind)
static std::string FillConstantArray (const ConstantArrayType *ct, const std::string &value, const uint64_t startAt)
static std::string GetValueOfValueInit (const QualType &t)
Protected Attributes inherited from clang::insights::CodeGenerator
LifetimeTracker mLifeTimeTracker {}
const Stmt * mLastStmt {}
const Expr * mLastExpr {}
bool mProcessingVarDecl {}
OutputFormatHelper & mOutputFormatHelper
LambdaStackType mLambdaStackThis
LambdaStackType & mLambdaStack
LambdaInInitCapture mLambdaInitCapture {LambdaInInitCapture::No}
ShowConstantExprValue mShowConstantExprValue {ShowConstantExprValue::No}
SkipVarDecl mSkipVarDecl {SkipVarDecl::No}
UseCommaInsteadOfSemi mUseCommaInsteadOfSemi {UseCommaInsteadOfSemi::No}
NoEmptyInitList mNoEmptyInitList
At least in case if a requires-clause containing T{} we don't want to get T{{}}.
const LambdaExpr * mLambdaExpr {}
std::optional< size_t > mCurrentVarDeclPos {}
std::optional< size_t > mCurrentCallExprPos {}
std::optional< size_t > mCurrentReturnPos {}
std::optional< size_t > mCurrentFieldPos {}
OutputFormatHelper * mOutputFormatHelperOutside
Helper output buffer for std::initializer_list expansion.
bool mRequiresImplicitReturnZero {}
Track whether this is a function with an imlpicit return 0.
bool mSkipSemi {}
ProcessingPrimaryTemplate mProcessingPrimaryTemplate {}
Static Protected Attributes inherited from clang::insights::CodeGenerator
static constexpr auto MAX_FILL_VALUES_FOR_ARRAYS
static std::map< std::string, bool > mSeenDecls {}
Detailed Description
A special generator for coroutines. It is only activated, if -show-coroutines-transformation is given as a command line option.
Definition at line 531 of file CodeGenerator.h.
Constructor & Destructor Documentation
CoroutinesCodeGenerator() [1/2]
clang::insights::CoroutinesCodeGenerator::CoroutinesCodeGenerator (OutputFormatHelper & _outputFormatHelper, const size_t posBeforeFunc) inline explicit
Definition at line 534 of file CodeGenerator.h.
CoroutinesCodeGenerator() [2/2]
clang::insights::CoroutinesCodeGenerator::CoroutinesCodeGenerator (OutputFormatHelper & _outputFormatHelper, const size_t posBeforeFunc, std::string_view fsmName, size_t suspendsCount, CoroutineASTData data) inline explicit
Definition at line 539 of file CodeGenerator.h.
~CoroutinesCodeGenerator()
clang::insights::CoroutinesCodeGenerator::~CoroutinesCodeGenerator () override
Definition at line 44 of file CoroutinesCodeGenerator.cpp.
References clang::insights::CodeGenerator::InsertArg(), clang::insights::OutputFormatHelper::InsertAt(), clang::insights::CoroutineASTData::mDoInsertInDtor, clang::insights::CoroutineASTData::mFrameType, clang::insights::CodeGenerator::mOutputFormatHelper, and RETURN_IF.
Member Function Documentation
GetFrameName()
std::string clang::insights::CoroutinesCodeGenerator::GetFrameName () const inline
Definition at line 567 of file CodeGenerator.h.
InsertArg() [1/9]
void clang::insights::CoroutinesCodeGenerator::InsertArg (const CallExpr * stmt) override
Definition at line 796 of file CoroutinesCodeGenerator.cpp.
References clang::insights::GetPlainName(), clang::insights::CodeGenerator::InsertArg(), clang::insights::CoroutineASTData::mFrameAccessDeclRef, clang::insights::asthelpers::Sizeof(), clang::insights::asthelpers::StaticCast(), and clang::insights::asthelpers::VoidTy().
InsertArg() [2/9]
void clang::insights::CoroutinesCodeGenerator::InsertArg (const CoreturnStmt * stmt) override
Definition at line 988 of file CoroutinesCodeGenerator.cpp.
References GetGlobalAST(), and kwCoReturnSpace.
InsertArg() [3/9]
void clang::insights::CoroutinesCodeGenerator::InsertArg (const CoroutineBodyStmt * stmt) override
Definition at line 704 of file CoroutinesCodeGenerator.cpp.
References clang::insights::asthelpers::StmtsContainer::Add(), clang::insights::OutputFormatHelper::AppendNewLine(), clang::insights::asthelpers::Break(), clang::insights::asthelpers::Case(), clang::insights::asthelpers::Catch(), clang::insights::asthelpers::Comment(), clang::insights::FINAL_SUSPEND_NAME, clang::insights::asthelpers::Goto(), clang::insights::asthelpers::If(), InsertArg(), kwInternalThis, clang::insights::asthelpers::Label(), clang::insights::CoroutineASTData::mInitialAwaitResumeCalledAccess, clang::insights::asthelpers::mkCompoundStmt(), clang::insights::CodeGenerator::mOutputFormatHelper, clang::insights::CoroutineASTData::mSuspendIndexAccess, clang::insights::CoroutineASTData::mThisExprs, clang::insights::asthelpers::Not(), clang::insights::asthelpers::Switch(), clang::insights::asthelpers::Throw(), and clang::insights::asthelpers::Try().
InsertArg() [4/9]
void clang::insights::CoroutinesCodeGenerator::InsertArg (const CoroutineSuspendExpr * stmt) override
Represents an expression that might suspend coroutine execution; either a co_await or co_yield expression.
Evaluation of this expression first evaluates its 'ready' expression. If that returns 'false': – execution of the coroutine is suspended – the 'suspend' expression is evaluated – if the 'suspend' expression returns 'false', the coroutine is resumed – otherwise, control passes back to the resumer. If the coroutine is not suspended, or when it is resumed, the 'resume' expression is evaluated, and its result is the result of the overall expression.
Definition at line 881 of file CoroutinesCodeGenerator.cpp.
References clang::insights::OutputFormatHelper::AppendNewLine(), GetGlobalAST(), clang::insights::CodeGenerator::InsertInstantiationPoint(), and clang::insights::CodeGenerator::mOutputFormatHelper.
InsertArg() [5/9]
void clang::insights::CoroutinesCodeGenerator::InsertArg (const CXXRecordDecl * stmt) override
Definition at line 775 of file CoroutinesCodeGenerator.cpp.
References clang::insights::CodeGenerator::InsertArg().
InsertArg() [6/9]
void clang::insights::CodeGenerator::InsertArg (const Decl * stmt) virtual
Reimplemented from clang::insights::CodeGenerator.
Definition at line 214 of file CodeGenerator.cpp.
InsertArg() [7/9]
void clang::insights::CoroutinesCodeGenerator::InsertArg (const ImplicitCastExpr * stmt) override
Definition at line 784 of file CoroutinesCodeGenerator.cpp.
References clang::insights::CodeGenerator::InsertArg(), and InsertArg().
Referenced by InsertArg(), InsertArg(), and InsertCoroutine().
InsertArg() [8/9]
void clang::insights::CoroutinesCodeGenerator::InsertArg (const OpaqueValueExpr * stmt) override
Definition at line 828 of file CoroutinesCodeGenerator.cpp.
References clang::insights::OutputFormatHelper::Append(), clang::insights::asthelpers::Assign(), clang::insights::CodeGenerator::BinaryOperator, clang::insights::BuildSuspendVarName(), clang::insights::CORO_FRAME_ACCESS, clang::insights::FindDeclRef(), clang::insights::FindValue(), clang::insights::OutputFormatHelper::InsertAt(), clang::insights::CoroutineASTData::mFrameAccessDeclRef, clang::insights::CodeGenerator::mOutputFormatHelper, and clang::insights::StrCat().
InsertArg() [9/9]
void clang::insights::CodeGenerator::InsertArg (const Stmt * stmt) virtual
Reimplemented from clang::insights::CodeGenerator.
Definition at line 215 of file CodeGenerator.cpp.
InsertCoroutine()
void clang::insights::CoroutinesCodeGenerator::InsertCoroutine (const FunctionDecl & fd, const CoroutineBodyStmt * body)
Definition at line 410 of file CoroutinesCodeGenerator.cpp.
References clang::insights::asthelpers::AccessMember(), clang::insights::asthelpers::AddrOf(), clang::insights::OutputFormatHelper::AppendCommentNewLine(), clang::insights::OutputFormatHelper::AppendNewLine(), clang::insights::OutputFormatHelper::AppendSemiNewLine(), clang::insights::asthelpers::Assign(), clang::insights::asthelpers::Bool(), clang::insights::BuildInternalVarName(), clang::insights::BuildTemplateParamObjectName(), clang::insights::asthelpers::Call(), clang::insights::asthelpers::CallMemberFun(), clang::insights::OutputFormatHelper::CloseScope(), clang::insights::asthelpers::Comment(), clang::insights::CORO_FRAME_ACCESS, clang::insights::CORO_FRAME_ACCESS_THIS, clang::insights::CORO_FRAME_NAME, clang::insights::CreateCoroFunctionDecl(), clang::insights::asthelpers::Dref(), clang::insights::EnableGlobalInsert(), clang::insights::asthelpers::Equal(), clang::insights::asthelpers::Function(), GetGlobalAST(), clang::insights::GetName(), clang::insights::HeaderNew, hlpDestroyFn, hlpResumeFn, clang::insights::asthelpers::If(), InsertArg(), clang::insights::CodeGenerator::InsertTemplateArg(), clang::insights::asthelpers::Int32(), clang::insights::MakeLineColumnName(), clang::insights::CoroutineASTData::mDestroyFnField, clang::insights::CoroutineASTData::mDoInsertInDtor, clang::insights::CoroutineASTData::mFrameAccessDeclRef, clang::insights::CoroutineASTData::mFrameType, clang::insights::CoroutineASTData::mInitialAwaitResumeCalledField, clang::insights::asthelpers::mkDeclRefExpr(), clang::insights::asthelpers::mkVarDeclRefExpr(), clang::insights::CodeGenerator::mOutputFormatHelper, clang::insights::CoroutineASTData::mPromiseField, clang::insights::CoroutineASTData::mResumeFnField, clang::insights::CoroutineASTData::mSuspendIndexField, clang::insights::CoroutineASTData::mThisExprs, clang::insights::asthelpers::New(), clang::insights::OutputFormatHelper::OpenScope(), clang::insights::asthelpers::Parameter(), clang::insights::asthelpers::Ptr(), clang::insights::asthelpers::Ref(), clang::insights::asthelpers::ReinterpretCast(), clang::insights::ReplaceAll(), clang::insights::SetFunctionBody(), clang::insights::StrCat(), clang::insights::asthelpers::Struct(), clang::insights::asthelpers::Variable(), and clang::insights::asthelpers::VoidTy().
InsertVarDecl()
bool clang::insights::CoroutinesCodeGenerator::InsertVarDecl (const VarDecl * vd) inline override protected virtual
Reimplemented from clang::insights::CodeGenerator.
Definition at line 570 of file CodeGenerator.h.
SkipSpaceAfterVarDecl()
bool clang::insights::CoroutinesCodeGenerator::SkipSpaceAfterVarDecl () inline override protected virtual
Reimplemented from clang::insights::CodeGenerator.
Definition at line 571 of file CodeGenerator.h.
The documentation for this class was generated from the following files:
CodeGenerator.h
CoroutinesCodeGenerator.cpp