C++Insights: clang::insights::CodeGenerator::LambdaScopeHandler Class Reference
clang::insights::CodeGenerator::LambdaScopeHandler Class Reference
#include "/home/builder/CodeGenerator.h"
Public Member Functions
LambdaScopeHandler (LambdaStackType &stack, OutputFormatHelper &outputFormatHelper, const LambdaCallerType lambdaCallerType)
~LambdaScopeHandler ()
Detailed Description
Definition at line 234 of file CodeGenerator.h.
Constructor & Destructor Documentation
LambdaScopeHandler()
clang::insights::CodeGenerator::LambdaScopeHandler::LambdaScopeHandler (LambdaStackType & stack, OutputFormatHelper & outputFormatHelper, const LambdaCallerType lambdaCallerType)
Definition at line 142 of file CodeGenerator.cpp.
References StackList< T >::push().
~LambdaScopeHandler()
clang::insights::CodeGenerator::LambdaScopeHandler::~LambdaScopeHandler ()
Definition at line 152 of file CodeGenerator.cpp.
References clang::insights::OutputFormatHelper::Append(), clang::insights::CodeGenerator::BinaryOperator, clang::insights::CodeGenerator::CallExpr, clang::insights::CodeGenerator::CXXMethodDecl, StackList< T >::empty(), clang::insights::CodeGenerator::InsertArg(), clang::insights::CodeGenerator::MemberCallExpr, clang::insights::CodeGenerator::mOutputFormatHelper, clang::insights::CodeGenerator::OperatorCallExpr, StackList< T >::pop(), clang::insights::CodeGenerator::PrintNamespace(), clang::insights::CodeGenerator::ReturnStmt, and clang::insights::CodeGenerator::VarDecl.
The documentation for this class was generated from the following files:
CodeGenerator.h
CodeGenerator.cpp