C++ Insights: runTest Namespace Reference
runTest Namespace Reference
Functions
def runCmd (cmd, data=None)
def cleanStderr (stderr, fileName=None)
def testCompare (tmpFileName, stdout, expectFile, f, args, time)
def testCompile (tmpFileName, f, args, fileName, cppStd)
def main ()
Variables
string mypath = '.'
Function Documentation
cleanStderr()
def runTest.cleanStderr (stderr, fileName = None)
Definition at line 28 of file runTest.py.
Referenced by main(), and testCompile().
main()
def runTest.main ()
Definition at line 120 of file runTest.py.
References cleanStderr(), runCmd(), testCompare(), and testCompile().
runCmd()
def runTest.runCmd (cmd, data = None)
Definition at line 17 of file runTest.py.
Referenced by main(), and testCompile().
testCompare()
def runTest.testCompare (tmpFileName, stdout, expectFile, f, args, time)
Definition at line 42 of file runTest.py.
Referenced by main().
testCompile()
def runTest.testCompile (tmpFileName, f, args, fileName, cppStd)
Definition at line 61 of file runTest.py.
References cleanStderr(), and runCmd().
Referenced by main().
Variable Documentation
mypath
string runTest.mypath = '.'
Definition at line 15 of file runTest.py.