C++ Insights: OptionDocumentationGenerator Namespace Reference
OptionDocumentationGenerator Namespace Reference
Functions
runCmd (cmd, data=None)
getDefaultIncludeDirs (cxx)
replaceSource (match)
cppinsightsLink (code, std='2a', options='')
replaceInsights (match, parser, args)
main ()
Function Documentation
cppinsightsLink()
OptionDocumentationGenerator.cppinsightsLink (code, std = '2a', options = '')
Definition at line 52 of file OptionDocumentationGenerator.py.
Referenced by replaceInsights().
getDefaultIncludeDirs()
OptionDocumentationGenerator.getDefaultIncludeDirs (cxx)
Definition at line 23 of file OptionDocumentationGenerator.py.
References runCmd().
Referenced by main(), and replaceInsights().
main()
OptionDocumentationGenerator.main ()
Definition at line 99 of file OptionDocumentationGenerator.py.
References getDefaultIncludeDirs(), main(), replaceInsights(), and runCmd().
Referenced by main().
replaceInsights()
OptionDocumentationGenerator.replaceInsights (match, parser, args)
Definition at line 72 of file OptionDocumentationGenerator.py.
References cppinsightsLink(), getDefaultIncludeDirs(), and runCmd().
Referenced by main().
replaceSource()
OptionDocumentationGenerator.replaceSource (match)
Definition at line 40 of file OptionDocumentationGenerator.py.
runCmd()
OptionDocumentationGenerator.runCmd (cmd, data = None)
Definition at line 12 of file OptionDocumentationGenerator.py.
Referenced by getDefaultIncludeDirs(), main(), and replaceInsights().