C++Insights: clang::ast_matchers Namespace Reference
clang::ast_matchers Namespace Reference
Functions
AST_MATCHER (FunctionDecl, isTemplateInstantiationPlain)
static bool IsMatchingCast (const CastKind kind)
return (insights::IsMacroLocation(insights::GetBeginLoc(Node))||insights::IsInvalidLocation(insights::GetBeginLoc(Node)))
Variables
const internal::VariadicDynCastAllOfMatcher< Decl, VarTemplateSpecializationDecl > varTemplateSpecDecl
const internal::VariadicDynCastAllOfMatcher< Decl, DecompositionDecl > decompositionDecl
const internal::VariadicDynCastAllOfMatcher< Type, DecltypeType > myDecltypeType
static const auto isTemplate
static const auto isAutoAncestor
const internal::VariadicDynCastAllOfMatcher< Decl, VarTemplateDecl > varTemplateDecl
Function Documentation
AST_MATCHER()
clang::ast_matchers::AST_MATCHER (FunctionDecl , isTemplateInstantiationPlain)
Definition at line 47 of file InsightsMatchers.h.
References SILENCE.
IsMatchingCast()
static bool clang::ast_matchers::IsMatchingCast (const CastKind kind) inline static
Definition at line 53 of file InsightsMatchers.h.
References clang::insights::GetBeginLoc(), clang::insights::IsInvalidLocation(), clang::insights::IsMacroLocation(), and SILENCE.
Referenced by clang::insights::CodeGenerator::InsertTemplateParameters().
return()
clang::ast_matchers::return (insights::IsMacroLocation(insights::GetBeginLoc(Node))||insights::IsInvalidLocation(insights::GetBeginLoc(Node)))
Referenced by OptionDocumentationGenerator::cppinsightsLink().
Variable Documentation
decompositionDecl
const internal::VariadicDynCastAllOfMatcher<Decl, DecompositionDecl> clang::ast_matchers::decompositionDecl
Definition at line 21 of file GlobalVariableHandler.cpp.
Referenced by clang::insights::GlobalVariableHandler::GlobalVariableHandler().
isAutoAncestor
const auto clang::ast_matchers::isAutoAncestor static
Initial value:
=
    hasAncestor(varDecl(anyOf(hasType(autoType().bind("autoType")),
                              hasType(qualType(hasDescendant(autoType().bind("autoType")))),
                              hasType(myDecltypeType().bind("dt")),
                              hasType(qualType(hasDescendant(myDecltypeType().bind("dt")))))))
Definition at line 31 of file InsightsMatchers.h.
isTemplate
const auto clang::ast_matchers::isTemplate static
Initial value:
= anyOf(hasAncestor(classTemplateDecl()),
                                     hasAncestor(functionTemplateDecl()),
                                     hasAncestor(classTemplateSpecializationDecl()))
Definition at line 26 of file InsightsMatchers.h.
Referenced by clang::insights::FunctionDeclHandler::FunctionDeclHandler(), clang::insights::GlobalVariableHandler::GlobalVariableHandler(), clang::insights::RecordDeclHandler::RecordDeclHandler(), and clang::insights::StaticAssertHandler::StaticAssertHandler().
myDecltypeType
const internal::VariadicDynCastAllOfMatcher< Type, DecltypeType > clang::ast_matchers::myDecltypeType
Definition at line 23 of file GlobalVariableHandler.cpp.
varTemplateDecl
const internal::VariadicDynCastAllOfMatcher< Decl, VarTemplateDecl > clang::ast_matchers::varTemplateDecl
Definition at line 24 of file TemplateHandler.cpp.
Referenced by clang::insights::GlobalVariableHandler::GlobalVariableHandler(), and clang::insights::TemplateHandler::TemplateHandler().
varTemplateSpecDecl
const internal::VariadicDynCastAllOfMatcher<Decl, VarTemplateSpecializationDecl> clang::ast_matchers::varTemplateSpecDecl
Definition at line 20 of file GlobalVariableHandler.cpp.
Referenced by clang::insights::GlobalVariableHandler::GlobalVariableHandler().