C++ Insights: clang::insights::details Namespace Reference
clang::insights::details Namespace Reference
Classes
class SimpleTypePrinter
SimpleTypePrinter a partially substitution of Clang's TypePrinter.
Functions
const char * Normalize (const std::string &arg)
uint64_t Normalize (const llvm::APInt &arg)
const char * Normalize (const llvm::APSInt &arg)
const char * Normalize (const StringRef &arg)
const auto & Normalize (const auto &arg)
void FPrintf (const char *fmt, const auto &... args)
static void BuildNamespace (std::string &fullNamespace, const NestedNameSpecifier *stmt, const IgnoreNamespace ignoreNamespace)
STRONG_BOOL (RemoveCurrentScope)
static std::string GetQualifiedName (const NamedDecl &decl, const RemoveCurrentScope removeCurrentScope=RemoveCurrentScope::Yes)
static std::string GetScope (const DeclContext *declCtx, const RemoveCurrentScope removeCurrentScope=RemoveCurrentScope::Yes)
static std::string GetName (QualType t, const Unqualified unqualified=Unqualified::No, const InsightsSuppressScope supressScope=InsightsSuppressScope::No)
std::string ConvertToBoolString (bool b)
Convert a boolean value to a string representation of "true" or "false".
void StrCat (std::string &ret, const auto &... args)
Function Documentation
BuildNamespace()
static void clang::insights::details::BuildNamespace (std::string & fullNamespace, const NestedNameSpecifier * stmt, const IgnoreNamespace ignoreNamespace) static
Definition at line 133 of file InsightsHelpers.cpp.
References clang::insights::GetUnqualifiedScopelessName(), kwTemplateSpace, and RETURN_IF.
Referenced by clang::insights::GetNestedName().
ConvertToBoolString()
std::string clang::insights::details::ConvertToBoolString (bool b) inline
Convert a boolean value to a string representation of "true" or "false".
Definition at line 25 of file InsightsStrCat.h.
Referenced by clang::insights::GetNoExcept(), clang::insights::Normalize(), and clang::insights::ToString().
FPrintf()
void clang::insights::details::FPrintf (const char * fmt, const auto &... args) inline
Definition at line 54 of file DPrint.h.
References Normalize().
Referenced by clang::insights::DPrint(), and clang::insights::Error().
GetName()
static std::string clang::insights::details::GetName (QualType t, const Unqualified unqualified = Unqualified::No, const InsightsSuppressScope supressScope = InsightsSuppressScope::No) static
Definition at line 899 of file InsightsHelpers.cpp.
References clang::insights::GetAsCPPStyleString(), clang::insights::details::SimpleTypePrinter::GetTypeString(), and clang::insights::ScopeHandler::RemoveCurrentScope().
Referenced by clang::insights::GetName(), clang::insights::GetTypeNameAsParameter(), clang::insights::GetUnqualifiedScopelessName(), clang::insights::CoroutinesCodeGenerator::InsertCoroutine(), clang::insights::CoroutineASTTransformer::VisitCoroutineBodyStmt(), and clang::insights::CoroutineASTTransformer::VisitDeclStmt().
GetQualifiedName()
static std::string clang::insights::details::GetQualifiedName (const NamedDecl & decl, const RemoveCurrentScope removeCurrentScope = RemoveCurrentScope::Yes) static
!< In some cases we need to keep the scope for a while, so don't remove the scope we are in right now.
Definition at line 440 of file InsightsHelpers.cpp.
References clang::insights::GetDeclContext(), and clang::insights::ScopeHandler::RemoveCurrentScope().
Referenced by clang::insights::GetName(), and GetScope().
GetScope()
static std::string clang::insights::details::GetScope (const DeclContext * declCtx, const RemoveCurrentScope removeCurrentScope = RemoveCurrentScope::Yes) static
Definition at line 455 of file InsightsHelpers.cpp.
References GetQualifiedName().
Referenced by clang::insights::GetName().
Normalize() [1/5]
const auto& clang::insights::details::Normalize (const auto & arg) inline
Definition at line 48 of file DPrint.h.
Normalize() [2/5]
uint64_t clang::insights::details::Normalize (const llvm::APInt & arg) inline
Definition at line 30 of file DPrint.h.
Normalize() [3/5]
const char* clang::insights::details::Normalize (const llvm::APSInt & arg) inline
Definition at line 36 of file DPrint.h.
References Normalize(), and clang::insights::ToString().
Normalize() [4/5]
const char* clang::insights::details::Normalize (const std::string & arg) inline
Definition at line 18 of file DPrint.h.
Referenced by FPrintf(), and Normalize().
Normalize() [5/5]
const char* clang::insights::details::Normalize (const StringRef & arg) inline
Definition at line 42 of file DPrint.h.
References Normalize().
StrCat()
void clang::insights::details::StrCat (std::string & ret, const auto &... args)
Definition at line 87 of file InsightsStrCat.h.
References clang::insights::Normalize().
Referenced by clang::insights::OutputFormatHelper::Append(), clang::insights::OutputFormatHelper::AppendCommentNewLine(), clang::insights::OutputFormatHelper::AppendNewLine(), clang::insights::OutputFormatHelper::AppendSemiNewLine(), clang::insights::CoroutinesCodeGenerator::InsertArg(), clang::insights::CoroutinesCodeGenerator::InsertCoroutine(), clang::insights::StrCat(), and clang::insights::CoroutineASTTransformer::VisitCoawaitExpr().
STRONG_BOOL()
clang::insights::details::STRONG_BOOL (RemoveCurrentScope)