C++ Insights: clang::insights::CfrontCodeGenerator::CfrontVtableData Struct Reference
clang::insights::CfrontCodeGenerator::CfrontVtableData Struct Reference
#include "CodeGenerator.h"
Public Member Functions
CfrontVtableData ()
VarDecl * VtblArrayVar (int size)
FieldDecl * VtblPtrField (const CXXRecordDecl *parent)
Public Attributes
QualType vptpTypedef
CXXRecordDecl * vtableRecorDecl
QualType vtableRecordType
FieldDecl * d
FieldDecl * f
Detailed Description
Definition at line 638 of file CodeGenerator.h.
Constructor & Destructor Documentation
CfrontVtableData()
clang::insights::CfrontCodeGenerator::CfrontVtableData::CfrontVtableData ()
Definition at line 42 of file CfrontCodeGenerator.cpp.
Member Function Documentation
VtblArrayVar()
VarDecl * clang::insights::CfrontCodeGenerator::CfrontVtableData::VtblArrayVar (int size)
Definition at line 61 of file CfrontCodeGenerator.cpp.
References clang::insights::asthelpers::ContantArrayTy(), clang::insights::asthelpers::Ptr(), clang::insights::asthelpers::Variable(), and vtableRecordType.
Referenced by clang::insights::EmitGlobalVariableCtors(), and clang::insights::InsertVtblPtr().
VtblPtrField()
FieldDecl * clang::insights::CfrontCodeGenerator::CfrontVtableData::VtblPtrField (const CXXRecordDecl * parent)
Definition at line 67 of file CfrontCodeGenerator.cpp.
References clang::insights::GetName(), clang::insights::asthelpers::mkFieldDecl(), clang::insights::asthelpers::Ptr(), and clang::insights::StrCat().
Referenced by clang::insights::CfrontCodeGenerator::InsertArg(), and clang::insights::InsertVtblPtr().
Member Data Documentation
d
FieldDecl* clang::insights::CfrontCodeGenerator::CfrontVtableData::d
Definition at line 658 of file CodeGenerator.h.
f
FieldDecl* clang::insights::CfrontCodeGenerator::CfrontVtableData::f
Definition at line 659 of file CodeGenerator.h.
vptpTypedef
QualType clang::insights::CfrontCodeGenerator::CfrontVtableData::vptpTypedef
Definition at line 646 of file CodeGenerator.h.
vtableRecorDecl
CXXRecordDecl* clang::insights::CfrontCodeGenerator::CfrontVtableData::vtableRecorDecl
Definition at line 656 of file CodeGenerator.h.
vtableRecordType
QualType clang::insights::CfrontCodeGenerator::CfrontVtableData::vtableRecordType
Definition at line 657 of file CodeGenerator.h.
Referenced by VtblArrayVar().
The documentation for this struct was generated from the following files:
CodeGenerator.h
CfrontCodeGenerator.cpp