C++ Insights: clang::insights::is< T > Struct Template Reference
clang::insights::is< T > Struct Template Reference
Handy helper to avoid longish comparisons.
#include "InsightsHelpers.h"
Public Member Functions
constexpr bool any_of (const auto &... ts) const
Public Attributes
T t
Detailed Description
template<typename T>
struct clang::insights::is< T >
Handy helper to avoid longish comparisons.
The idea is taken from a talk from Björn Fahller at NDC TechTown 2019: Modern Techniques for Keeping Your Code DRY (https://youtu.be/YUWuNpxZa5k)
if(is{v}.any_of(A, B, C)) { ... }
Definition at line 385 of file InsightsHelpers.h.
Member Function Documentation
any_of()
template<typename T > constexpr bool clang::insights::is< T >::any_of (const auto &... ts) const inline constexpr
Definition at line 389 of file InsightsHelpers.h.
References clang::insights::is< T >::t.
Referenced by clang::insights::CodeGenerator::FormatCast(), clang::insights::GetCastName(), and clang::insights::CodeGenerator::InsertMethodBody().
Member Data Documentation
t
template<typename T > T clang::insights::is< T >::t
Definition at line 387 of file InsightsHelpers.h.
Referenced by clang::insights::is< T >::any_of().
The documentation for this struct was generated from the following file:
InsightsHelpers.h