C++ Insights: clang::insights::DeclsHolder Struct Reference
clang::insights::DeclsHolder Struct Reference
Public Member Functions
void push_back (const VarDecl *vd)
void JoinDeclsAndMoveDecls ()
void FindAllVarDecls (const Stmt *stmt)
const decl_vector_t & GetDecls () const
bool ContainsDecl (const Decl *decl) const
Public Attributes
decl_vector_t mMoveDecls {}
decl_vector_t mDecls {}
recordDecl_vector_t mEmptyRecordDecls {}
recordDecl_vector_t mRecordDecls {}
this_vector_t mThisExprs {}
int mSuspendsCount {}
bool EmulateEmpty {true}
Detailed Description
Definition at line 272 of file CoroutinesCodeGenerator.cpp.
Member Function Documentation
ContainsDecl()
bool clang::insights::DeclsHolder::ContainsDecl (const Decl * decl) const inline
Definition at line 339 of file CoroutinesCodeGenerator.cpp.
References clang::insights::Contains().
FindAllVarDecls()
void clang::insights::DeclsHolder::FindAllVarDecls (const Stmt * stmt) inline
Traverse the whole CoroutineBodyStmt to find all appearing VarDecl. These need to be rerouted to the coroutine frame and hence prefixed by something like __f->. For that reason we only look for VarDecls directly appearing in the body, CallExpr will be skipped.
Definition at line 301 of file CoroutinesCodeGenerator.cpp.
GetDecls()
const decl_vector_t& clang::insights::DeclsHolder::GetDecls () const inline
Definition at line 328 of file CoroutinesCodeGenerator.cpp.
JoinDeclsAndMoveDecls()
void clang::insights::DeclsHolder::JoinDeclsAndMoveDecls () inline
Definition at line 292 of file CoroutinesCodeGenerator.cpp.
push_back()
void clang::insights::DeclsHolder::push_back (const VarDecl * vd) inline
Definition at line 284 of file CoroutinesCodeGenerator.cpp.
References clang::insights::AddToVarNamePrefixMap(), and clang::insights::CORO_FRAME_ACCESS.
Referenced by clang::insights::CoroutinesCodeGenerator::InsertCoroutine().
Member Data Documentation
EmulateEmpty
bool clang::insights::DeclsHolder::EmulateEmpty {true}
Definition at line 282 of file CoroutinesCodeGenerator.cpp.
Referenced by clang::insights::CoroutinesCodeGenerator::InsertArg().
mDecls
decl_vector_t clang::insights::DeclsHolder::mDecls {}
Definition at line 275 of file CoroutinesCodeGenerator.cpp.
Referenced by clang::insights::CoroutinesCodeGenerator::InsertArg().
mEmptyRecordDecls
recordDecl_vector_t clang::insights::DeclsHolder::mEmptyRecordDecls {}
Definition at line 277 of file CoroutinesCodeGenerator.cpp.
mMoveDecls
decl_vector_t clang::insights::DeclsHolder::mMoveDecls {}
Definition at line 274 of file CoroutinesCodeGenerator.cpp.
mRecordDecls
recordDecl_vector_t clang::insights::DeclsHolder::mRecordDecls {}
Definition at line 278 of file CoroutinesCodeGenerator.cpp.
Referenced by clang::insights::CoroutinesCodeGenerator::InsertArg().
mSuspendsCount
int clang::insights::DeclsHolder::mSuspendsCount {}
Definition at line 281 of file CoroutinesCodeGenerator.cpp.
mThisExprs
this_vector_t clang::insights::DeclsHolder::mThisExprs {}
Definition at line 280 of file CoroutinesCodeGenerator.cpp.
Referenced by clang::insights::CoroutinesCodeGenerator::InsertArg().
The documentation for this struct was generated from the following file:
CoroutinesCodeGenerator.cpp