C++ Insights: clang::insights::asthelpers::StmtsContainer Struct Reference
clang::insights::asthelpers::StmtsContainer Struct Reference
! A helper type to have a container for ArrayRef
#include "ASTHelpers.h"
Public Member Functions
StmtsContainer ()=default
StmtsContainer (std::initializer_list< const Stmt * > stmts)
void clear ()
void Add (const Stmt *stmt)
void AddBodyStmts (Stmt *body)
operator ArrayRef< Stmt * > ()
Public Attributes
SmallVector< Stmt *, 64 > mStmts {}
Detailed Description
! A helper type to have a container for ArrayRef
Definition at line 63 of file ASTHelpers.h.
Constructor & Destructor Documentation
StmtsContainer() [1/2]
clang::insights::asthelpers::StmtsContainer::StmtsContainer () default
StmtsContainer() [2/2]
clang::insights::asthelpers::StmtsContainer::StmtsContainer (std::initializer_list< const Stmt * > stmts) inline
Definition at line 68 of file ASTHelpers.h.
References Add().
Member Function Documentation
Add()
void clang::insights::asthelpers::StmtsContainer::Add (const Stmt * stmt) inline
Definition at line 77 of file ASTHelpers.h.
References mStmts.
Referenced by clang::insights::CoroutinesCodeGenerator::InsertArg(), clang::insights::CfrontCodeGenerator::InsertArg(), and StmtsContainer().
AddBodyStmts()
void clang::insights::asthelpers::StmtsContainer::AddBodyStmts (Stmt * body)
Definition at line 724 of file ASTHelpers.cpp.
Referenced by clang::insights::EmitGlobalVariableCtors(), clang::insights::CodeGenerator::HandleLocalStaticNonTrivialClass(), and clang::insights::InsertVtblPtr().
clear()
void clang::insights::asthelpers::StmtsContainer::clear () inline
Definition at line 75 of file ASTHelpers.h.
References mStmts.
operator ArrayRef< Stmt * >()
clang::insights::asthelpers::StmtsContainer::operator ArrayRef< Stmt * > () inline
Definition at line 86 of file ASTHelpers.h.
References mStmts.
Member Data Documentation
mStmts
SmallVector<Stmt*, 64> clang::insights::asthelpers::StmtsContainer::mStmts {}
Definition at line 65 of file ASTHelpers.h.
Referenced by Add(), clear(), and operator ArrayRef< Stmt * >().
The documentation for this struct was generated from the following files:
ASTHelpers.h
ASTHelpers.cpp